### ISSUE TITLE
Highlighting Question

### ISSUE THREAD

**Issue by aarondfrancis** [Stillat/vscode-antlers-language-server#11]
Hey 👋 

First of all thanks for writing and maintaining this! It's a great resource.

I do have a question about syntax highlighting in one specific code block:

![image](https://user-images.githubusercontent.com/881931/125648986-f6baf3e7-eb45-433a-bcf3-8273cf96fd04.png)

This was taken from the Statamic docs. Any ideas why `name` and `style` are different?

Thanks!

**Comment by JohnathonKoster** [comment]
Hi there!

This extension takes two approaches to syntax highlighting:

1. A general tmLanguage based approach - this is applied first, and is the same across all projects
2. A more granular parsing-based approach - this is applied on top of the tmLanguage syntax highlighting

With the more granular parsing, this extension will look at your project's blueprints, as well as how the Antlers tags appear in the document, to determine "what kind" of styling to apply to it. In this case it looks like one of the default syntax rules has taken priority for `name`.

**Comment by aarondfrancis** [comment]
Thanks for the response! I'm familiar with the tmLanguage approach, but not sure what the second approach is.

This snippet was taken from the Statamic docs and pasted into a scratch file, so there is no project blueprint to inspect, which makes me think it might be a tmLangauge issue? Maybe that `name` is being picked up as a keyword where it shouldn't be?

Any ideas?

Thanks!

**Comment by JohnathonKoster** [comment]
Doing a quick inspect, `name` is being treated differently than `style` from the tm grammar in this instance:

![style_inspect](https://user-images.githubusercontent.com/5232890/129816111-d339d3c9-875f-4a3d-b643-91005191623e.jpg)

I will review the grammar file to see what should be done for out-of-box consistency - most likely will demote `name` so it's picked up by the `variable.other` rule

**Comment by aarondfrancis** [comment]
Thanks for reopening, and for the helpful links. I'll give the semantic highlighting one a read for sure. I'm building https://torchlight.dev, so that seems kinda important 😂

**Comment by JohnathonKoster** [comment]
Not a problem! I've been experimenting with torchlight.dev - it's pretty awesome, and will be keeping an eye on it!

**Comment by aarondfrancis** [comment]
Ha! Small world. Lemme know if you ever have any questions or I can help with anything 🤝

**Comment by JohnathonKoster** [comment]
`name` has been removed from the `statamic-tag-native-variable` list in the grammar files to bring consistency here.

I will leave this open as I need to set aside some time to go through the entirety of the grammar some more and fine-tune the rules

**Comment by aarondfrancis** [comment]
Amazing, thank you!

**Comment by JohnathonKoster** [comment]
@aarondfrancis 

Just a courtesy notice that the grammar has changed dramatically, and will be part of a production release of the extension soon

https://github.com/Stillat/vscode-antlers-language-server/blob/feature/parser-rewrite/client/syntaxes/antlers.json

**Comment by aarondfrancis** [comment]
awesome, thank you for the heads up @JohnathonKoster!

**Comment by JohnathonKoster** [comment]
Going to close this for now. Feel free to re-open/add comments/add new issues if you have any more questions regarding the highlighting 🙂
