### ISSUE TITLE
[Feature Request] Ignore a specific file

### ISSUE THREAD

**Issue by lokmanm** [Stillat/vscode-antlers-language-server#16]
Hello @JohnathonKoster, first of all thank you for all the work you put in the extension.

I have cases where I work with `.antlers.xml` or other formats where I need to mix antlers with another file extension and I have to do `Save without formatting` on those files as it gets messy real quick. 

Is there a way to introduce something like what `eslint` has comments to ignore  `/* eslint-disable */` a specific file from formatting ?

Sorry for making an issue on this but I couldn't find anything else to submit a feature request.

Thanks

**Comment by JohnathonKoster** [comment]
Thanks for the idea! I will look into it and see if I can get it done in time for a larger release planned end of Jan/early Feb!

**Comment by lokmanm** [comment]
Awesome, thanks a lot 🙌

**Comment by JohnathonKoster** [comment]
@lokmanm 

Wanted to get your feedback before locking the feature down. This approach allows anyone to specific a list of extensions the formatter should ignore (`xml` added as a default). When the formatter detects these extensions, the formatting request is simply ignored.

![ignore_extensions](https://user-images.githubusercontent.com/5232890/149594389-42a74058-006f-45e4-bc41-e441a65dcea2.png)

**Comment by lokmanm** [comment]
Ah this is way better than I imagined. Its way clear to define upfront the extensions and less typing on files.

Thanks a lot for this @JohnathonKoster  🙏
