### ISSUE TITLE
Strange highlighting behaviour with complex Antlers tag

### ISSUE THREAD

**Issue by ebeauchamps** [Stillat/vscode-antlers-language-server#2]
From the home.antlers.html view of the Cool Writings starter kit:

```{{ excerpt | widont ?? content | strip_tags | safe_truncate:160:...}}```

![Capture d’écran 2021-05-17 à 22 58 07](https://user-images.githubusercontent.com/1823359/118555820-6a6b6300-b763-11eb-9b2a-c49bf359f534.png)

MAC OS 10.12.6

**Comment by ebeauchamps** [comment]
Another example:
```{{ is_current || is_parent ?= 'font-medium text-gray-800' }}```

![Capture d’écran 2021-05-17 à 23 10 43](https://user-images.githubusercontent.com/1823359/118557220-2b3e1180-b765-11eb-9297-1239fc0f36c7.png)

**Comment by ebeauchamps** [comment]
And perhaps this one could need some love, too (look at the "next_page"):
```
{{ paginate }}
        {{ if prev_page || next_page }}
        <div class="flex justify-between text-xl -mx-16 pt-16 font-bold">
            <a href="{{ prev_page }}" class="{{ ! prev_page ?= 'opacity-25' }}">
                &larr; Back to the future
            </a>
            <a href="{{ next_page }}">
                Forward to the past &rarr;
            </a>
        </div>
        {{ /if }}
        {{ /paginate }}
```

![Capture d’écran 2021-05-17 à 23 18 55](https://user-images.githubusercontent.com/1823359/118558012-55440380-b766-11eb-959e-0a2c3500eee9.png)

**Comment by JohnathonKoster** [comment]
@ebeauchamps Great finds! Will be with the 1.0.18 update  🎉
