### ISSUE TITLE
Linter interprets comments 

### ISSUE THREAD

**Issue by klickreflex** [Stillat/vscode-antlers-language-server#23]
With the recent update I started to get loads of new linting errors. Most are false positives from antlers comments:

<img width="574" alt="CleanShot 2022-02-28 at 15 14 28@2x" src="https://user-images.githubusercontent.com/435825/155998003-7e46d67e-4e62-46e2-8bdf-0c3dfc20f328.png">

**Comment by JohnathonKoster** [comment]
Thanks for the bug report!

The issue with the comments being parsed as Antlers has been addressed in version 2.0.7 (I also expanded the list of allowed types for the `url` parameter). This version is now available within the extension marketplace

**Comment by klickreflex** [comment]
Thank **you** for that fast fix, very appreciated <3
