### ISSUE TITLE
Formatting removes semicolon (:) after assets.

### ISSUE THREAD

**Issue by Pixney-William** [Stillat/vscode-antlers-language-server#24]
When using the assets fieldtype you get an array of assets. 

**You can either loop it doing** 
```
{{ assets }}
    ....
{{ /assets }}
```

**But you can also pick an individual asset by doing** 
`{{ asset:0 }}` or `{{ asset:1 }}`

In the last scenario, when formatting the semicolon is removed and we end up with : `{{ asset0 }} or {{ asset1 }}`

**Comment by JohnathonKoster** [comment]
Thanks for the report!

This has been resolved with version 2.0.10 for Visual Studio Code and version 1.0.11 for the CLI version :)
