### ISSUE TITLE
Formatting CLI: Nothing happens

### ISSUE THREAD

**Issue by marcorieser** [Stillat/vscode-antlers-language-server#25]
If I run `antlersformat format --f="/Users/marco/localweb/statamic-firefly/resources/views/home.antlers.html"` or even `antlersformat format --f="/Users/marco/localweb/statamic-firefly/resources/views/home.antlers.html" --dd` nothing happens.

Node: v17.1.0
NPM: 8.3.0

Am I doing something wrong?

**Comment by JohnathonKoster** [comment]
Hi there! I'll check into the `--f` option later this evening my time, but in the meantime you can use the simpler version that does not require also managing the output path:

```
antlersformat format "path/here/without/switch"
```

The `--dd` option can also be used with this version.

**Comment by JohnathonKoster** [comment]
Resolved with CLI version 1.0.12
