### ISSUE TITLE
Formatter messes up condition (with Prettier)

### ISSUE THREAD

**Issue by marcorieser** [Stillat/vscode-antlers-language-server#26]
In VS Code the condition `{{ if page:collection != 'pages' }}` gets messed up in following template:
```html
<header class="pt-2.5 pb-6 md:pt-6 md:pb-8 lg:pt-8 lg:pb-10">
    <div class="custom-grid">
        <div class="custom-content-area-boxed custom-subgrid items-center gap-y-4 lg:gap-y-0">
            <div class="col-span-6 flex justify-start lg:justify-end lg:order-1 lg:col-span-4">
                <a href="{{ site:url }}">
                    <img src="/svg/logo.svg" alt="{{ site:name }}" class="max-h-[75px] translate-y-[7%] lg:max-h-[none]" />
                </a>
            </div>
            <div class="col-span-6 flex justify-end xl:col-span-3 xl:justify-start lg:order-3">
                {{ partial:layout/burger class="text-midnight_express hover:text-neon_nazar transition-opacity duration-300" visible="opacity-0" }}
            </div>
            <div class="col-span-full flex flex-col gap-4 lg:col-span-5 lg:order-2">
                {{ if page:collection != 'pages' }}
                    <div class="text-2xl font-light lowercase text-midnight_express">{{ page:collection }}</div>
                {{ /if }}
                <h1 class="h1 truncate lowercase">{{ title }}</h1>
            </div>
        </div>
    </div>
</header>
```
to 
```html
<header class="pt-2.5 pb-6 md:pt-6 md:pb-8 lg:pt-8 lg:pb-10">
    <div class="custom-grid">
        <div class="custom-content-area-boxed custom-subgrid items-center gap-y-4 lg:gap-y-0">
            <div class="col-span-6 flex justify-start lg:order-1 lg:col-span-4 lg:justify-end">
                <a href="{{ site:url }}">
                    <img src="/svg/logo.svg" alt="{{ site:name }}"
                        class="max-h-[75px] translate-y-[7%] lg:max-h-[none]" />
                </a>
            </div>
            <div class="col-span-6 flex justify-end lg:order-3 xl:col-span-3 xl:justify-start">
                {{ partial:layout/burger class="text-midnight_express
                hover:text-neon_nazar transition-opacity duration-300" visible="opacity-0" }}
            </div>
            <div class="col-span-full flex flex-col gap-4 lg:order-2 lg:col-span-5">
                {{ if page:collection != city du }}
                    <div class="text-2xl font-light lowercase text-midnight_express">
                        {{ page:collection }}
                    </div>
                {{ /if }}
                <h1 class="h1 truncate lowercase">{{ title }}</h1>
            </div>
        </div>
    </div>
</header>
```

I'm using the Antlers Toolbox with the setting "Antlers Format With Prettier First If Available" enabled. I installed the Tailwind CSS Formatter https://github.com/tailwindlabs/prettier-plugin-tailwindcss. Without the setting "Antlers Format With Prettier First If Available" enabled the formatting is great.

Running the prettier formatting manually and then formatting with Antlers Toolbox works perfect.
Running `prettier --write _header.antlers.html && antlersformat format _header.antlers.html` works too. Maybe a larger delay between the two commands would solve the issue.

**Comment by lightbringer93** [comment]
I have the same problem. It messes with my short if statement `{{ is_current ?= 'text-primary-700 ' }}`
From
`
<div class="flex items-center space-x-2">
    {{ locales current_first="false" }}
        <a class="{{ is_current ?= 'text-primary-700 ' }}text-stone-500 hover:text-primary-600 focus:text-primary-700 transition-colors  ease-in-out duration-150"
            href="{{ permalink }}">
            {{ locale:short }}
        </a>
        {{ if not last }}
            <span class="text-stone-400">|</span>
        {{ /if }}
    {{ /locales }}
</div>`
to
`
<div class="flex items-center space-x-2">
    {{ locales current_first="false" }}
        <a class="{{ is_current ?=  ?= 'text-primary-7 }}text-stone-500 hover:text-primary-600 focus:text-primary-700 transition-colors  ease-in-out duration-150"
            href="{{ permalink }}">
            {{ locale:short }}
        </a>
        {{ if not last }}
            <span class="text-stone-400">|</span>
        {{ /if }}
    {{ /locales }}
</div>`

**Comment by JohnathonKoster** [comment]
I'll see what I can do!

(probably remove Antlers entirely before going to Prettier)

**Comment by JohnathonKoster** [comment]
@marcorieser  @lightbringer93 

I'm doing some final validation/testing, but I think I go this issue sorted. It will now remove all Antlers code from the document, format it with Prettier, put the Antlers back and then format it with the Antlers formatter.

This does some weird things with the Undo history (not sure what/if I can do about that right now), but at least it does not trash the document now :)

https://user-images.githubusercontent.com/5232890/162630859-3b92a827-60fc-4a6d-8e86-671429582514.mp4

**Comment by JohnathonKoster** [comment]
Improvements made in:

* Antlers Toolbox Version 2.0.12
