### ISSUE TITLE
Inconsistent indentation of switch tag

### ISSUE THREAD

**Issue by montemartin** [Stillat/vscode-antlers-language-server#27]
Thank you SOOOO much for making the new switch tag (and set vars!) happen!!! I've been working with both and I'm getting some odd results from the formatter. The indentation of cases seems to be malfunctioning, and the space before the opening brackets and tag name gets removed. 

This is my inital experience: 
<img width="510" alt="CleanShot 2022-04-05 at 09 41 20@2x" src="https://user-images.githubusercontent.com/6987789/161779630-559c20e9-0056-43e7-98a1-2a3acfe4f62f.png">

When switch is Inside the entries loop each case and the closing are always indented 6 spaces, while the opening tag is indented correctly. This behaviour seems to happen anytime the switch is inside another bracket pair. 

If I move the switch case outside the loop it indents the cases as far past the opening bracket as the bracket itself, plus six extra spaces. I tried testing in an empty file and got similar behaviour, plus without the variable name the opening space gets removed:

Before formatting:
<img width="360" alt="CleanShot 2022-04-05 at 10 03 18@2x" src="https://user-images.githubusercontent.com/6987789/161784554-6618b724-8bcd-4ea6-a8e1-e840fd5e50d1.png">

After formatting:
<img width="468" alt="CleanShot 2022-04-05 at 10 03 52@2x" src="https://user-images.githubusercontent.com/6987789/161784677-00e384db-49e3-4c09-b2f7-05838f23f3c3.png">

**Comment by JohnathonKoster** [comment]
Resolved with:

* CLI Version 1.0.12
* Antlers Toolbox Version 2.0.12
