### ISSUE TITLE
Code being deleted when closing partial outside section

### ISSUE THREAD

**Issue by montemartin** [Stillat/vscode-antlers-language-server#28]
When working on a template I mistakenly tried to close the wrong partial and ran across what I think is a weirdly specific bug. 

When a partial is linked inside a section tag, then closed after the closing section tag all code except the open and closing section tags is deleted. This is the minimal code I've been able to reproduce it with. 

```
{{ section:intro }}
    {{ partial:intro }}
{{ /section:intro }}
{{ partial:background }}
        {{# code #}}
{{ /partial:intro }}
```

When the above is saved/formatted the result is
```
{{ section:intro }}

{{ /section:intro }}
```

I initially thought is was related to the section and partial name being the same, but it happens no matter what the names are.

**Comment by JohnathonKoster** [comment]
@montemartin  Interesting... I'll have to make it so it doesn't attempt to format when the document is invalid.

```
{{ section:intro }}
    {{ partial:intro }} ================
{{ /section:intro }}                                        |
{{ partial:background }}                               |=> These shouldn't be interleaved like this.
        {{# code #}}                                         |
{{ /partial:intro }}  =================
```

If you update the final closing tag to be `{{ /partial:background }}` it should work:

```
{{ section:intro }}
    {{ partial:intro }}
{{ /section:intro }}
{{ partial:background }}
    {{# code #}}
{{ /partial:background }}
```

To have it work currently, you could make the first partial tag self-closing:

```
{{ section:intro }}
    {{ partial:intro /}}
{{ /section:intro }}
{{ partial:background }}
    {{# code #}}
{{ /partial:intro }}              <= Now this just becomes a closing tag not paired to anything
```

**Comment by montemartin** [comment]
In this case closing the wrong tag was just a typo so it's not causing a problem. Figured I'd report it since it was pretty jarring to see the entire file (mostly) disappear on save.

**Comment by JohnathonKoster** [comment]
Definitely can see how that'd be jarring! Great catch, and thanks for reporting it! <3

**Comment by montemartin** [comment]
Not sure whether this sheds light on the problem or makes it worse, but I've been going through some templates and reformatting. In my HTML head file I had the following comment `{{# {{ partial:layouts/meta-og }} #}}`. Everything _after_ that in the file was deleted.

**Comment by JohnathonKoster** [comment]
Resolved with:

* CLI Version 1.0.12
* Antlers Toolbox Version 2.0.12
