### ISSUE TITLE
Unexpected type supplied to modifier

### ISSUE THREAD

**Issue by stephenmeehanuk** [Stillat/vscode-antlers-language-server#30]
Hi

I'm using Antlers Toolbox v2.0.14, I'm seeing this error.

```
[{
	"resource": "/Users/xxxxxxxx/Repositories/xxxxxxxx/resources/views/structured-data/_local-business.antlers.html",
	"owner": "_generated_diagnostic_collection_name_#1",
	"severity": 4,
	"message": "[ANTLR_508] Unexpected type supplied to modifier . Expected string got array.",
	"source": "antlers",
	"startLineNumber": 42,
	"startColumn": 55,
	"endLineNumber": 42,
	"endColumn": 60
}]
```

It's referring to this

```
"latitude":"{{ company:long_lat | explode:, | first }}",
```

`first` is highlighted.

What's the correct way to fix this?

It's worth mentioning, the code works as it is. 

I'd just like to know if there's a way to stop the error from showing up.

**Comment by JohnathonKoster** [comment]
I'm not able to reproduce this on 2.0.14 (which was released earlier today to address this) -- but can on 2.0.13 and below.

Would you be able to verify the version number here:

![verify_here](https://user-images.githubusercontent.com/5232890/165819929-839dd240-462b-4836-8e62-2b4eacf43b6c.png)

If you are still experiencing this issue after verifying that you are on 2.0.14, would you mind sharing more of the template that is triggering this? Thanks!

**Comment by stephenmeehanuk** [comment]
I was sure I restarted VS Code after updating the plugin, however, this morning the error is no longer showing. 2.0.14 has fixed this issue. Thanks for your help.
