### ISSUE TITLE
Inconsistent final newline formatting

### ISSUE THREAD

**Issue by stefan-galescu** [Stillat/vscode-antlers-language-server#31]
When using the formatter, saving a file that has a final newline results in removing that newline. When saving the file again, the newline is added back. I've tested with two other formatters (Prettier and HTML Language Features) and none seem to replicate the issue. You can watch a video reproduction here: https://cln.sh/lFxegoU3bFEWLFZHQzFO.

**Comment by JohnathonKoster** [comment]
Fix available in the following releases:

* Formatting CLI `1.0.16`
* Antlers Toolbox (VS Code) `2.1.2`
