### ISSUE TITLE
Antlers in <script> tag gets scrambled

### ISSUE THREAD

**Issue by Gitsack** [Stillat/vscode-antlers-language-server#32]
Hi :) I'm aware that this might be a issue of me using the plugin incorrectly, but I'm not sure whats the correct way.

There is a project where script tags inside an antlers.html file are being used. When including antlers inside the JS and saving the file, the antlers expression gets scrambled - for example:

```js
const element = {{ value }};
```

is being parsed to:

```js
const element = __ANTLR_6c3aad4c - b12c - 4456 - a62c - c94d0f2effac;
```

So I guess the plugin's UUID for this element is inserted in the background.

A fallback to this is inserting a template configuration comment at the start of the file:
```js
{{#
    @format false
#}}
```

Is there another setting in vscode that can be tweaked, maybe in combination with other formatters?

---

Setup:
- Runtime parser
- Not formatted with Antlers first

**Comment by JohnathonKoster** [comment]
This has been resolved with the following releases:

* VS Code version `2.0.16`
* Antlers Formatter CLI version `1.0.13`

**Comment by Gitsack** [comment]
Wow thanks for the quick fix :) 

It's not scrambled anymore. The only thing is, at least when I tried it now: The curly brackets are formatted in an object-like matter:

```js
const element = {
    {
        value
    }
};
```

Unfortunately, this breaks parsing of the antlers tags again.

**Comment by JohnathonKoster** [comment]
Do you have any additional formatting addons installed? If not, would you mind sending more of the template that is causing the issue?

If you don't want to share it publicly you can also email me: john@stillat.com

**Comment by Gitsack** [comment]
Yes, so I think this is caused by the script tag being wrapped in an `{{if}}` condition. This is a minimal version where the error happens in my instance:

```html
{{ if conditionHere }}
<script>
    const test = {{ data }};
</script>
{{ /if }}
```

Afaik, only this plugin should format html if I setup everything correctly.

**Comment by JohnathonKoster** [comment]
@Gitsack  Thanks for the investigation into this and providing a sample that easily reproduces the issue (it helps a ton!)

This has been corrected in the following versions:

* VS Code extension: 2.0.17
* Formatter CLI: 1.0.14

**Comment by Gitsack** [comment]
Awesome! Thanks, it works. :)
