### ISSUE TITLE
Formatter cuts off after commented curly braces

### ISSUE THREAD

**Issue by globalexport** [Stillat/vscode-antlers-language-server#36]
The formatter seems to behave dangerously when commenting antlers tags. 

**Impacted Products**
Which Antlers Toolbox products does this bug apply to?

- [?] Antlers Toolbox for VS Code
- [X] Antlers Toolbox for VS Code Formatter

Using Antlers Toolbox: v2.2.0
Visual Studio Code: v1.69.1

- create test.antlers.html
- add content like below
- format document 

Error occuring here
```
<div>
  {{# {{ partial src="something" }} #}}
  <h1>Help! I get deleted!</h1>
</div>
```

Result would be just this:
```
<div>
  {{# {{ partial src="something" }} #}}
```

Error not occuring here:
```
<div>
  {{# {{ partial src="something" }} #}}
  {{# This mighty comment protects you from deletion! #}}
  <h1>Thank you for saving me!</h1>
</div>
```

**Expected behavior**
Do nothing as the format is already right.

**Observed behaviour**
Loss of code due to formatting. Only a second comment (`{{#  #}}`) stops this behaviour.

**Comment by JohnathonKoster** [comment]
Thanks for the report! A fix is available (with test coverage) for the following versions

* Antlers Toolbox for VS Code 2.2.1
* `antlers-formatter` 1.1.2
* `prettier-plugin-antlers` 1.1.9

**Comment by JohnathonKoster** [comment]
@globalexport 

This new issue is corrected in the following:

* Antlers Toolbox for VS Code: 2.2.2
* `antlers-formatter`: 1.1.3
* `prettier-plugin-antlers`: 1.1.10

Hopefully this covers the comments and trailing literals for now :)

**Comment by globalexport** [comment]
Perfect, thank you!
