### ISSUE TITLE
When looping over view data: Cannot read properties of undefined (reading 'forEach')

### ISSUE THREAD

**Issue by schwartzmj** [Stillat/vscode-antlers-language-server#37]
**Describe the bug**
In the template we're looping over "view" data and when saving the file, it doesn't format the document and VS Code's "Output" tab in the integrated terminal emits:

```
["ERROR" - 12:41:19 PM] Error formatting document.
["ERROR" - 12:41:19 PM] Cannot read properties of undefined (reading 'forEach')
TypeError: Cannot read properties of undefined (reading 'forEach')
```

The template itself renders correctly in the browser without issue.

**Impacted Products**
Which Antlers Toolbox products does this bug apply to?

- [ ] Antlers Toolbox for VS Code
- [ ] Antlers Toolbox for VS Code Formatter
- [ ] Formatter CLI
- [x] Antlers Prettier Plugin
- [ ] Antlers Syntax Highlighting (external systems - not VS Code)

**Versions and Other Plugins/Extensions**
"prettier": "^2.6.2",
"prettier-plugin-antlers": "^1.1.10",
"prettier-plugin-tailwindcss": "^0.1.12"

**To Reproduce**
Use the frontmatter and template code below.

I've removed two SVG tags before each `<p>{{ value }}</p>` element since you won't have those SVGs in your project, but that shouldn't matter for this reproduction.

For what it's worth, I also tried the following syntaxes when looping and received the same error.
- `{{ foreach:view:tips:do }}`
- `{{ view:tips:do }}`

**Expected behavior**
Document formats with no error in output.

**If submitting a formatting bug, please include the template contents below as well as an attachment**
```antlers
---
tips:
    do:
        - Lorem ipsum 1
        - Lorem ipsum 2
    dont:
        - Lorem ipsum 1
        - Lorem ipsum 2
---

<section class="theme-container mx-auto py-20">
    <h2 class="text-center text-4xl lg:text-5xl font-extrabold tracking-tight text-gray-900">Tips</h2>
    <div class="text-center max-w-lg mx-auto text-lg text-gray-500 mt-6">
        <p>
            Lorem ipsum
        </p>
    </div>
    <div class="grid gap-8 lg:grid-cols-2 mt-16 text-gray-500">
        <div class="max-w-lg mx-auto">
            <h3 class="text-center text-3xl font-extrabold tracking-tight text-gray-900">Things to consider</h3>
            <ul class="space-y-6 mt-6">
                {{ foreach:view.tips.do }}
                    <li class="flex items-start space-x-2">
                        <p>{{ value }}</p>
                    </li>
                {{ /foreach:view.tips.do }}
            </ul>
        </div>
        <div class="max-w-lg mx-auto">
            <h3 class="text-center text-3xl font-extrabold tracking-tight text-gray-900">Things to avoid</h3>
            <ul class="space-y-6 mt-6">
                {{ foreach:view.tips.dont }}
                    <li class="flex items-start space-x-2">
                        <p>{{ value }}</p>
                    </li>
                {{ /foreach:view.tips.dont }}
            </ul>
        </div>
    </div>
</section>
```

**Additional context**

**Comment by JohnathonKoster** [comment]
Resolved in:

- Antlers Toolbox for VS Code: 2.2.4
- `antlers-language-server`: 1.0.4
- `antlers-formatter`: 1.1.4
- `prettier-plugin-antlers`: 1.1.11
