### ISSUE TITLE
[ANTLR_201] Unexpected string start while parsing variable path. String literals must be within array accessors.

### ISSUE THREAD

**Issue by ryanscherler** [Stillat/vscode-antlers-language-server#38]
**Describe the bug**
It seems that the ANTLRS server doesn't like how I am accessing this property? (See attached)

<img width="1081" alt="Screen Shot 2022-08-03 at 3 03 57 PM" src="https://user-images.githubusercontent.com/881938/182720609-df3951ca-3dfa-4245-8656-bf9d3516fad6.png">

> I am using the regex version of the statamic antlers engine and also using the Spatie responsive image plugin and wanted access to the default image:src for a `poster` attribute on the video tag. This was the only way I could figure out access to it.

Is there a way to suppress this error?

**Impacted Products**
Which Antlers Toolbox products does this bug apply to?

- [x] Antlers Toolbox for VS Code
- [ ] Antlers Toolbox for VS Code Formatter
- [ ] Formatter CLI
- [ ] Antlers Prettier Plugin
- [ ] Antlers Syntax Highlighting (external systems - not VS Code)

**Versions and Other Plugins/Extensions**
2.3.0

**Comment by JohnathonKoster** [comment]
@ryanscherler 

Thanks for the report! Unfortunately, there is no way to disable specific error codes within the server. I've updated the language server's parser to remove this false positive and should be good to go if you update to `2.3.1` 🙂

**Comment by ryanscherler** [comment]
Awesome thanks @JohnathonKoster - this is such a helpful toolbox for building Statamic sites!
