### ISSUE TITLE
Can't find the antlersFormatWithPrettierFirstIfAvailable on the Settings UI

### ISSUE THREAD

**Issue by lepaliscot** [Stillat/vscode-antlers-language-server#39]
**Describe the bug**
I'm using Prettier VS Code Extension as default formatter with the Tailwindcss Prettier Plugin and also have Antlers Toolbox for VS Code Formatter installed

**Impacted Products**
Which Antlers Toolbox products does this bug apply to?

- [ ] Antlers Toolbox for VS Code
- [X] Antlers Toolbox for VS Code Formatter
- [ ] Formatter CLI
- [ ] Antlers Prettier Plugin
- [ ] Antlers Syntax Highlighting (external systems - not VS Code)

**Versions and Other Plugins/Extensions**
Prettier VS Extension 9.5.0
Prettier Plugin Tailwindcss plugin ^0.1.13
Prettier Plugin ^2.7.1

**To Reproduce**
- Install Prettier extension
- Install Antlers extension
- Instal Prettier Plugin in my project via npm

**Expected behavior**
I want to format my antlers templates with the Antlers Formatter and then with Prettier

**Additional context**

**Comment by JohnathonKoster** [comment]
The `antlersFormatWithPrettierFirstIfAvailable` has been deprecated, and is no longer available in the newest versions of the VS Code extension.

To format with Prettier on the newest versions, you will need to install and configure the Antlers Prettier plugins separately: https://www.npmjs.com/package/prettier-plugin-antlers

**Comment by lepaliscot** [comment]
Hi John, thanks for your help.
C.
