### ISSUE TITLE
Feature Request: Respect users `html.format` settings

### ISSUE THREAD

**Issue by montemartin** [Stillat/vscode-antlers-language-server#4]
Thanks for your plugin! It blows the VSCode HTML formatter out of the water! 

However I find myself missing a couple features of the default formatter. Specifically [`html.format.wrapAttributes`](https://code.visualstudio.com/docs/languages/html#_formatting), which is super helpful when using TailwindCSS.  

It would be great if your plugin could respect those settings by default.

**Comment by JohnathonKoster** [comment]
@montemartin  Thanks for the feedback! I've added a compatibility that will bring in all the default VS Code html.format settings (except for the templating ones - those are causing weird results).

This will be available in 1.0.19

**Comment by montemartin** [comment]
Just updated and man this sweet. Thanks so much for your hard work!
