### ISSUE TITLE
vscodeLanguageIds : missing info in the documentation

### ISSUE THREAD

**Issue by jimblue** [Stillat/vscode-antlers-language-server#42]
Hey,
Just a simple question, what is `vscodeLanguageIds`  option for in **prettier-plugin-antlers** ?
Tks 🙏🏼

**Comment by JohnathonKoster** [comment]
That configuration option helps Prettier pick which parser it should use. Here is the relevant Prettier documentation on this option: 
 https://github.com/prettier/prettier-vscode/wiki/Custom-File-Extension-Configuration#custom-language-identifier

When using Prettier in VS Code, and you have both the prettier-plugin-antlers plugin installed and the Antlers Toolbox (https://antlers.dev/) installed, setting that to `antlers` helps things to "just work." The Antlers Toolbox extension provides the `antlers` language ID to VS Code.

Hope this helps!

**Comment by jimblue** [comment]
Oh I see it's  an option for **Prettier VsCode** than you for the links, it does help 🙏🏼 !
