### ISSUE TITLE
Formating problems with Prettier and Antlers

### ISSUE THREAD

**Issue by jimblue** [Stillat/vscode-antlers-language-server#43]
**Impacted Products**
Which Antlers Toolbox products does this bug apply to?

- [ ] Antlers Toolbox for VS Code
- [ ] Antlers Toolbox for VS Code Formatter
- [ ] Formatter CLI
- [X] Antlers Prettier Plugin
- [ ] Antlers Syntax Highlighting (external systems - not VS Code)

**Versions and Other Plugins/Extensions**

```md
- prettier-plugin-antlers -> **1.1.13**
```

**Describe the bug**

Hello,

First thank you, this set of Antlers tools,  it's just amazing. 🤟🏼 
Yesterday I've managed to format all my Antlers templates with **Prettier** and **prettier-plugin-antlers**.
The result looks good for most of the templates but I've encounter 2 kinds or formating problems.

### First problem

This one is really strange, for some templates, **Prettier** doen't output the same formating and each run.
**Prettier** change the format from **version A** to **version B** and then from **version B** to **version A**...
For exemple, on each **Prettier** run it changes the following from:

**version A**
```twig
{{ user:isnt roles="admin|editor" }}{{ 404 }}{{ /user:isnt }}
```

to:

**version B**
```twig
{{ user:isnt roles="admin|editor" }}
  {{ 404 }}
{{ /user:isnt }}
```

I've got the same problem for:

**version A**
```twig
{{ topics }}{{ title }}{{ /topics }}
```

**version B**
```twig
{{ topics }}
  {{ title }}
{{ /topics }}
```

### Second problem

This one happen only for one template, my `layout.antlers.html`:

```antlers
<!DOCTYPE html>
<html lang="{{ site:locale }}">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=5, viewport-fit=cover" />
    <meta name="theme-color" content="#000000" />
    {{ seo_pro:meta }}
    {{ yield:preconnect }}
    <link rel="icon" href="/favicon.ico" sizes="any" />
    <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
    <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
    <link rel="manifest" href="/manifest.webmanifest" />
    {{ webpack:style name="print.css" loading="print" }}
    {{ webpack:style name="critical.css" loading="inline" }}
    {{ webpack:style name="main.css" preload="true" }}
    {{ webpack }}
    {{ yield:page_scripts }}
  </head>
  <body>
    {{ partial:common/patterns/page-transition }}
    {{ partial:common/patterns/navbar }}
    <main>{{ template_content }}</main>
    {{ partial:common/patterns/social }}
    {{ partial:common/patterns/footer }}
    {{ partial:common/patterns/search-modal }}
    {{ yield:inline_script }}
  </body>
</html>
```

When I format this file with **Prettier**, the output looks completely broken:

```antlers
<!DOCTYPE html>
<html lang="{{ site:locale }}">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=5, viewport-fit=cover" />
    <meta name="theme-color" content="#000000" />
    {{ seo_pro:meta }} {{ yield:preconnect }}
    <link rel="icon" href="/favicon.ico" sizes="any" />
    <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
    <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
    <link rel="manifest" href="/manifest.webmanifest" />
    {{ webpack:style name="print.css" loading="print" }} {{ webpack:style name="critical.css" loading="inline" }} {{ webpack:style name="main.css" preload="true" }} {{ webpack }}
    {{ yield:page_scripts }}
  </head>
  <body>
    {{ partial:common/patterns/page-transition }} {{ partial:common/patterns/navbar }}
    <main>{{ template_content }}</main>
    {{ partial:common/patterns/social }} {{ partial:common/patterns/footer }} {{ partial:common/patterns/search-modal }} {{ yield:inline_script }}
  </body>
</html>
```

Thank you for your help, cheers 🍻

**Comment by JohnathonKoster** [comment]
Hi there!

Would you be able to share your prettier formatting settings/preferences? Thanks!

**Comment by jimblue** [comment]
Sure here it is:

**prettier.config.js**
```js
module.exports = {
  arrowParens: 'avoid',
  semi: false,
  singleQuote: true,
  trailingComma: 'all',
  overrides: [
    {
      files: ['*.antlers.html', '*.antlers.php'],
      options: {
        parser: 'antlers',
      },
      vscodeLanguageIds: ['antlers'],
    },
    {
      files: ['*.blade.php'],
      options: {
        parser: 'blade',
        tabWidth: 2,
      },
      vscodeLanguageIds: ['blade'],
    },
  ],
}
```

**Comment by JohnathonKoster** [comment]
Thanks!

Interesting - I will keep digging on my end to see what combination of settings causes this behavior (cannot replicate on a test that has no prettierrc or adjusted configs).

Will update here as I learn more :)

**Comment by jimblue** [comment]
You're welcome! 🙂

I've forgot to tell that I got the exact same **Prettier** ouput problems when formating trough **VsCode** command `Format Document` or from **Prettier** CLI `npx prettier --write resources/views/blog/cards/_card-small.antlers.html`.

I hope this help 🤞🏼

**Comment by JohnathonKoster** [comment]
I've been able to replicate this only if the Antlers plugin is not being loaded when Prettier is invoked.

Can you verify that you have a `.prettierrc` file at the root of your project with the following contents?

```json
{
    "plugins": [
        "./node_modules/prettier-plugin-antlers/"
    ],
    "overrides": [
        {
            "files": "*.antlers.html",
            "vscodeLanguageIds": ["antlers"],
            "options": {
                "parser": "antlers"
            }
        }
    ]
}
```

**Comment by jimblue** [comment]
@JohnathonKoster I was using a `prettier.config.js`config file.
But I've try with a `.prettierrc` file at the root of my project like so :
```json
{
  "arrowParens": "avoid",
  "semi": false,
  "singleQuote": true,
  "trailingComma": "all",
  "plugins": ["./node_modules/prettier-plugin-antlers/", "./node_modules/prettier-plugin-blade/"],
  "overrides": [
    {
      "files": ["*.antlers.html", "*.antlers.php"],
      "options": {
        "parser": "antlers"
      },
      "vscodeLanguageIds": ["antlers"]
    },
    {
      "files": ["*.blade.php"],
      "options": {
        "parser": "blade",
        "tabWidth": 2
      },
      "vscodeLanguageIds": ["blade"]
    }
  ]
}
```
I still got the exact same problem.

**Comment by jimblue** [comment]
I've also just tried with the exact same config you suggested and the problem is still there.

**Comment by JohnathonKoster** [comment]
Are you able to verify that Prettier is using the Antlers plugin in the Prettier debug output?

When I was able to reproduce, it produced output similar to:

```
{
  "filepath": "formatter_test\\resources\\views\\layout.antlers.html",
  "parser": "html", <== should say antlers here
  "useTabs": false,
  "tabWidth": 4,
  "endOfLine": "lf",
  "plugins": [
    "formatter_test\\node_modules\\prettier-plugin-antlers"
  ]
}
```

**Comment by jimblue** [comment]
Yes with this [prettier.config.js](https://github.com/Stillat/vscode-antlers-language-server/issues/43#issuecomment-1211305668) at the root of my projet, the plugin is properly used. Here is a screenshot of the Prettier output:
<img width="844" alt="Screenshot 2022-08-21 at 20 52 57" src="https://user-images.githubusercontent.com/10623367/185806611-1e60d05e-71f8-4cbe-94e0-2e6a528dfadf.png">
Also the because most of my Antlers template are correctly formated with Prettier let me think it's not because of the config.

**Comment by jimblue** [comment]
Here is a repo that reproduce the problem : https://github.com/jimblue/bug-formating-antlers-with-prettier

**Comment by JohnathonKoster** [comment]
@jimblue 

Thanks for the repo! That helps so much. It appears that its due to the printWidth of `200`. Updating the config to:

```js
module.exports = {
  arrowParens: 'avoid',
  semi: false,
  singleQuote: true,
  trailingComma: 'all',
  printWidth: 80,
  overrides: [
    {
      files: ['*.antlers.html', '*.antlers.php'],
      options: {
        parser: 'antlers',
      },
      vscodeLanguageIds: ['antlers'],
    },
    {
      files: ['*.blade.php'],
      options: {
        parser: 'blade',
        tabWidth: 2,
      },
      vscodeLanguageIds: ['blade'],
    },
  ],
}

```

produces much better output across the files

**Comment by jimblue** [comment]
@JohnathonKoster the output is worst on my side:
the unfomated source:

```antlers
<!DOCTYPE html>
<html lang="{{ site:short_locale }}">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
    <meta name="theme-color" content="#000000" />
    {{ seo_pro:meta }}
    {{ yield:preconnect }}
    <link rel="icon" href="/favicon.ico" sizes="any" />
    <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
    <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
    <link rel="manifest" href="/manifest.webmanifest" />
    {{ webpack:style name="print.css" loading="print" }}
    {{ webpack:style name="critical.css" loading="inline" }}
    {{ webpack:style name="main.css" preload="true" }}
    {{ webpack }}
    {{ yield:page_scripts }}
  </head>
  <body>
    {{ partial:common/patterns/skip-link }}
    {{ partial:common/patterns/page-transition }}
    {{ partial:common/patterns/navbar }}
    <main>{{ template_content }}</main>
    {{ partial:common/patterns/social }}
    {{ partial:common/patterns/footer }}
    {{ partial:common/patterns/search-modal }}
    {{ yield:inline_script }}
  </body>
</html>
```

The prettier output with `printWidth : 80`:

```antlers
<!DOCTYPE html>
<html lang="{{ site:short_locale }}">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, viewport-fit=cover"
    />
    <meta name="theme-color" content="#000000" />
    {{ seo_pro:meta }} {{ yield:preconnect }}
    <link rel="icon" href="/favicon.ico" sizes="any" />
    <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
    <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
    <link rel="manifest" href="/manifest.webmanifest" />
    {{ webpack:style name="print.css" loading="print" }}
    {{ webpack:style name="critical.css" loading="inline" }}
    {{ webpack:style name="main.css" preload="true" }} {{ webpack }}
    {{ yield:page_scripts }}
  </head>
  <body>
    {{ partial:common/patterns/ skip -link }}
    {{ partial:common/patterns/page-transition }}
    {{ partial:common/patterns/navbar }}
    <main>{{ template_content }}</main>
    {{ partial:common/patterns/social }} {{ partial:common/patterns/footer }}
    {{ partial:common/patterns/search-modal }} {{ yield:inline_script }}
  </body>
</html>
```

As you can see it's messing up a lot of things like:

the space added breaking the template name:  `{{ partial:common/patterns/ skip -link }}`

or

the partial list not in a list anymore:
```antlers
{{ partial:common/patterns/social }} {{ partial:common/patterns/footer }}
    {{ partial:common/patterns/search-modal }} {{ yield:inline_script }}
```

**Comment by jimblue** [comment]
IMO the line break between `{{ }}`should depends on Prettier.

**Comment by JohnathonKoster** [comment]
I'm looking into the spacing with the partial name as a separate issue.

**Comment by jimblue** [comment]
> I'm looking into the spacing with the partial name as a separate issue.

Sure make sens. Do you want me to create a new issue ?

**Comment by JohnathonKoster** [comment]
nah - I'll handle it here :)

Gonna reopen this

**Comment by JohnathonKoster** [comment]
I apologize for all the back and forth! Sometimes really hard to replicate/figure some of this stuff out with how complex it can get! Hang tight - gonna get you fixed up 🎉

**Comment by JohnathonKoster** [comment]
@jimblue 

I've just published `1.1.15` of the Prettier plugin if you want to take it for a spin. This version corrects the issue with the partial names.

The internal logic that prevents this:

```
<main>{{ template_content }}</main>
```

from becoming:

```
<main>
     {{ template_content }}
</main>
```

was a bit too aggressive, so has been adjusted and should now stop all of your partial tags from collapsing to single lines

**Comment by JohnathonKoster** [comment]
> IMO the line break between `{{ }}`should depends on Prettier.

I get what you're saying, but things get incredibly nuanced real quick. A good example is something like the following:

```antlers
<div>
            <{{ as or 'a' }} class="something {{ as or 'a' }} {{ as }}">
                    {{ as or 'a' }} {{ loop }}
    <{{ nested }}>
<span>{{ title }}</span>
                    </{{ nested }}          >
            {{ /loop }}</{{ as or 'a' }}></div>
```

which gets formatted to:

```antlers
<div>
    <{{ as or 'a' }} class="something {{ as or 'a' }} {{ as }}">
        {{ as or 'a' }}
        {{ loop }}
            <{{ nested }}>
                <span>{{ title }}</span>
            </{{ nested }}>
        {{ /loop }}
    </{{ as or 'a' }}>
</div>
```

Constructing dynamic elements from Antlers/etc. gets really complicated and is part of the reason that it will force certain breaking behavior depending on the context.

**Comment by jimblue** [comment]
Zillion of ❤️ to you for `v1.1.15`, this is totally fixed now !
Bravo and thank you 👏🏼
