### ISSUE TITLE
Formatter removing space after curly brackets

### ISSUE THREAD

**Issue by pdipatrizio** [Stillat/vscode-antlers-language-server#44]
**Describe the bug**
The formatter removes the space after curly brackets of my `switch` statement. The overall formatting also seems unorganized (in my opinion) but I'm not sure if that part is actually buggy or if it's expected behavior.

**Impacted Products**
- [x] Antlers Toolbox for VS Code Formatter

**Versions and Other Plugins/Extensions**
Antlers Toolbox v2.3.2

**To Reproduce**
Run _Format Document With..._ on unformatted code (provided below) and select _Antlers Toolbox_.

**Expected behavior**
I expected the space between `{{` and `switch` to not be removed. I also expected the overall formatting of the Antlers code to be more organized.

**Template Contents BEFORE formatting**
```
{{#
    @name h1
    @desc The typography h1 partial to render an h1 with `class`, `as`, `color` and `content` attributes.
    @param* content The h1 content.
    @param as The wrapping element. Defaults to `h1`.
    @param color Set a custom text color utility. Falls back to `text-neutral`.
    @param class Add custom CSS classes.
#}}

<!-- /typography/_h1.antlers.html -->
<{{ as or 'h1' }}
    class="{{ switch
                (
                    (format == 'eyebrow') => '',
                    () => 'text-2xl md:text-4xl font-bold leading-tight'
                )
            }}
        {{ color or 'text-neutral' }} {{ class }}">
    {{ content | nl2br }}
    </{{ as or 'h1' }}>
<!-- End: /typography/_h1.antlers.html -->
```

**Template Contents AFTER formatting**
```
{{#
    @name h1
    @desc The typography h1 partial to render an h1 with `class`, `as`, `color` and `content` attributes.
    @param* content The h1 content.
    @param as The wrapping element. Defaults to `h1`.
    @param color Set a custom text color utility. Falls back to `text-neutral`.
    @param class Add custom CSS classes.
#}}

<!-- /typography/_h1.antlers.html -->
<{{ as or 'h1' }} class="{{switch(
   (format == 'eyebrow') => '',
   () => 'text-2xl md:text-4xl font-bold leading-tight') }}
        {{ color or 'text-neutral' }} {{ class }}">
    {{ content | nl2br }}
</{{ as or 'h1' }}>
<!-- End: /typography/_h1.antlers.html -->
```

**Additional Context**
Here are some relevant settings from my settings.json. I added all the `html.format` options while trying to figure out why the formatter wasn't working as expected but they didn't make any difference while using the Antlers Formatter. I also tried restarting VS Code.
```
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.formatOnSave": true,
  "antlersLanguageServer.languageVersion": "runtime",
  "antlersOverrideHtmlComments": true,
  "html.format.wrapAttributes": "force-aligned",
  "html.format.templating": true,
  "html.format.indentHandlebars": true,
  "[html]": {
    "editor.defaultFormatter": "stillat-llc.vscode-antlers"
  }
```

**Comment by JohnathonKoster** [comment]
Thanks for the report and additional information! I agree the formatting of those nested statements could use some love.

Will set aside some time later this week to see what can be done to add some polish here 🙂

**Comment by JohnathonKoster** [comment]
Notes for self:

* Removal of space was by design to auto-correct issues in legacy syntax. Cannot remove, but may have it look at the currently active language version
* Improve indentation detection on nested switch formatting.

**Comment by JohnathonKoster** [comment]
Notes for self:

* Removal of space was by design to auto-correct issues in legacy syntax. Cannot remove, but may have it look at the currently active language version
* Improve indentation detection on nested switch formatting.

**Comment by JohnathonKoster** [comment]
The indentation of the `switch` operator has been improved in the following versions:

* Antlers Toolbox for VS Code: `2.3.3.`
* `antlers-formatter`: `1.1.10`
* `prettier-plugin-antlers`: `1.1.14`

The provided input will now produce:

```antlers
{{#
    @name h1
    @desc The typography h1 partial to render an h1 with `class`, `as`, `color` and `content` attributes.
    @param* content The h1 content.
    @param as The wrapping element. Defaults to `h1`.
    @param color Set a custom text color utility. Falls back to `text-neutral`.
    @param class Add custom CSS classes.
#}}

<!-- /typography/_h1.antlers.html -->
<{{ as or 'h1' }} class="{{ switch(
                              (format == 'eyebrow') => '',
                              () => 'text-2xl md:text-4xl font-bold leading-tight') }}
        {{ color or 'text-neutral' }} {{ class }}">
    {{ content | nl2br }}
</{{ as or 'h1' }}>
<!-- End: /typography/_h1.antlers.html -->
```

This new behavior keeps the `switch` branches closer together, which is more in line with their behavior in other circumstances. The leading space is no longer removed for `switch` or `list.` The remaining wrapping/indentation is currently working as intended for how dynamic the provided example is.
