### ISSUE TITLE
Contextual Autosuggestions Not Working Properly

### ISSUE THREAD

**Issue by pdipatrizio** [Stillat/vscode-antlers-language-server#45]
When I start typing `{{ partial: }}`, the autosuggestions don't seem to come from my project's resources.

![Screen Shot 2022-08-15 at 4 46 33 PM](https://user-images.githubusercontent.com/19377737/184843801-0e07d446-e66d-46f9-b295-22bf7a280dd6.png)

I tried executing _Reload Statamic Project Details_ but got the same results. The docs mention opening VS Code to just the `resources/` directory but when I do that and try reloading the project details, I get this error:

`Command 'Antlers: Reload Statamic Project Details' resulted in an error (command 'extension.antlersLanguageServer.reloadProjectDetails' not found)`

Not sure what other details I could provide that would be helpful. Just let me know and I'll follow up as soon as possible.

**Comment by JohnathonKoster** [comment]
Do you have other extensions installed that may also be loaded (sometimes they can interacted in strange ways) - I am having troubles reproducing the command error.

The suggestions that do show up do come from the language server itself, so it does seem like that is loading correctly. You can try searching for this setting and disabling it:

<img width="542" alt="image" src="https://user-images.githubusercontent.com/5232890/184905158-818b973c-a1a6-49e2-92ed-78e77cdaa2b6.png">

Disabling that setting will prevent the suggestions in your screenshot from appearing. Restarting VS Code/Reloading that file and triggering completions again should show other items in that list.

**Comment by marflow** [comment]
Having the same problem as pdipatrizio, also for collections. I tried and removed extensions, then reinstalled VSC and Antlers Toolbox fresh, empty settings except Project Manager and Antlers Toolbox, but no success. (One out of twenty or so tries I might get correct partial suggestions when entering a blank after the colon `{{ partial:  }}`. (MPB M1, Ventura, VSC and extensions up to date.) Thanks for suggestions, what I could try.

**Comment by JohnathonKoster** [comment]
> Having the same problem as pdipatrizio, also for collections. I tried and removed extensions, then reinstalled VSC and Antlers Toolbox fresh, empty settings except Project Manager and Antlers Toolbox, but no success. (One out of twenty or so tries I might get correct partial suggestions when entering a blank after the colon `{{ partial: }}`. (MPB M1, Ventura, VSC and extensions up to date.) Thanks for suggestions, what I could try.

Hi there! I've located the root problem for this particular issue, and am working on a fix to be released in the next update. In the meantime, you should be able to get the correct suggestions by forcing closing the suggestions window (`esc` key) and then forcing them to appear again (`Cmd + I` on macOS and `Ctrl + Space` on Windows)

**Comment by JohnathonKoster** [comment]
Note to self: the root issue is the context/position resolver mistakes the left character for a `space` under some situations, causing it to either suggest tag names, or parameter names instead of the contextual tag suggestions

**Comment by marflow** [comment]
Hello Jonathon, Thanks for the quick reply. Glad you found the issue and will include a fix in the next Toolbox version. In the meantime, your suggested workaround helps me out :) Thanks for all the hard work you put in the Statamic ecosystem with the Antlers Engine, Toolbox and articles – very much appreciated!

**Comment by JohnathonKoster** [comment]
Resolved in `2.3.9`

**Comment by marflow** [comment]
Thanks a lot Jonathon – working perfect now and it is just brilliant!

**Comment by pdipatrizio** [comment]
Great news!! Just tested and it works perfectly :)
