### ISSUE TITLE
With the Prettier plugin, multiple comment lines are reduced to a single one

### ISSUE THREAD

**Issue by helloDanuk** [Stillat/vscode-antlers-language-server#46]
**Describe the bug**
Using the Antlers Prettier plugin, comments with multiple lines are reduced to a single line as you can see in the screenshots below. Further the second command is appended to the line before.

<img width="700" alt="before save" src="https://user-images.githubusercontent.com/8265902/185792546-33df8dbf-9ad0-420d-a545-4a4f996c20f0.png">
<img width="672" alt="after save" src="https://user-images.githubusercontent.com/8265902/185792550-5b0e59c4-1a7c-4f4c-aa46-5f20b1eaa49c.png">

 
**Impacted Products**
Which Antlers Toolbox products does this bug apply to?

- [ ] Antlers Toolbox for VS Code
- [ ] Antlers Toolbox for VS Code Formatter
- [ ] Formatter CLI
- [x] Antlers Prettier Plugin
- [ ] Antlers Syntax Highlighting (external systems - not VS Code)

**Versions and Other Plugins/Extensions**
Here is my nearly empty settings.json from vs code:

```json
{
  "editor.formatOnSave": true,
  "editor.formatOnType": true,
  "editor.formatOnPaste": true,
  "antlersLanguageServer.languageVersion": "runtime",
  "editor.defaultFormatter": "esbenp.prettier-vscode"
}
```

**To Reproduce**
- create a new statamic site
- install prettier, prettier-plugin-tailwind and prettier-plugin-antlers
- Add some comments an a view/layout-file
- run prettier on file save

**Expected behavior**
Fix indentation but keep multi-line comments

**If submitting a formatting bug, please include the template contents below as well as an attachment**

```antlers
{{#
    @name The template name.
    @desc A human-friendly description for your awesome template.
    @entry collectionName
    @collection collectionName
#}}
<!DOCTYPE html>
<html lang="{{ site:short_locale }}">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>{{ title ?? site:name }}</title>
    <link rel="stylesheet" href="{{ mix src='css/tailwind.css' }}" />
</head>
<body class="bg-gray-100 leading-normal text-gray-800 font-sans ">
    <div class="mx-auto flex flex-col items-center justify-center px-2 lg:min-h-screen">
        {{ template_content }}
        {{#
            Lorem
            ipsum
            dolor
        #}}
    </div>
    <script src="{{ mix src='/js/site.js' }}"></script>
</body>
</html>
```

**Comment by JohnathonKoster** [comment]
I can replicate this only if the Antlers plugin has not been loaded. Are you able to view your Prettier debug output in VS Code to ensure that it is actually being used?

I can replicate this if the output is similar to:

```
["INFO" - 9:43:18 AM] Prettier Options:
{
  "filepath": "formatter_test\\resources\\views\\layout.antlers.html",
  "parser": "html",
  "useTabs": false,
  "tabWidth": 4,
  "endOfLine": "lf",
  "plugins": [
    "formatter_test\\node_modules\\prettier-plugin-antlers",
    "formatter_test\\node_modules\\prettier-plugin-blade"
  ]
}
```

Adding this to a `.prettierrc` at the root of the project:

```json
{
    "plugins": [
        "./node_modules/prettier-plugin-antlers/"
    ],
    "overrides": [
        {
            "files": "*.antlers.html",
            "vscodeLanguageIds": ["antlers"],
            "options": {
                "parser": "antlers"
            }
        }
    ]
}
```

should cause the Prettier debug output to produce something similar to the following:

```
["INFO" - 9:44:40 AM] Prettier Options:
{
  "filepath": "formatter_test\\resources\\views\\layout.antlers.html",
  "parser": "antlers",
  "useTabs": false,
  "tabWidth": 4,
  "endOfLine": "lf",
  "plugins": [
    "formatter_test\\node_modules\\prettier-plugin-antlers"
  ]
}
```

**Comment by helloDanuk** [comment]
Thank you very much for pointing me to the solution. Now it works!

With `"editor.formatOnPaste": true,` there is still a notification in VS Code. But with formatOnSave it works anyway.

<img width="472" alt="Bildschirmfoto 2022-08-21 um 22 38 38" src="https://user-images.githubusercontent.com/8265902/185810018-3831dc96-de90-4a8d-b94f-007d3f835a4d.png">


```json
{
  "editor.formatOnPaste": true,
  "editor.formatOnSave": true,
  "editor.formatOnType": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "antlersLanguageServer.languageVersion": "runtime"
}
```
