### ISSUE TITLE
Antlers if condition inside `<script>` causes incorrect indentation

### ISSUE THREAD

**Issue by duncanmcclean** [Stillat/vscode-antlers-language-server#47]
**Describe the bug**
If you have an Antlers file with the contents mentioned below, every time you save the code in the `<script>` will be indented.

To workaround the issue you have to 'Save without formatting'.

**Impacted Products**
Which Antlers Toolbox products does this bug apply to?

- [X] Antlers Toolbox for VS Code
- [ ] Antlers Toolbox for VS Code Formatter
- [ ] Formatter CLI
- [X] Antlers Prettier Plugin _(I think!)_
- [ ] Antlers Syntax Highlighting (external systems - not VS Code)

**Versions and Other Plugins/Extensions**

* Antlers Toolbox: 2.3.5
* Prettier: 9.8.0

**To Reproduce**

Create an `.antlers.html` file with the below contents:

```antlers
<div>
    <!-- ... -->
</div>

<script>
    const localLocations = JSON.parse(`{{ local_locations | to_json }}`)

    let linkColour = `{{ if segment_2 === 'location-1' }} #20332E {{ else }} #073C4A {{ /if }}`
</script>
```

^ the above is a simplified template that still allows for reproduction.

**Expected behavior**
I would have expected it not to indent every time I save.

**If submitting a formatting bug, please include the template contents below as well as an attachment**
Have attached above...

**Additional context**
I've recorded a quick video to demonstrate: https://www.loom.com/share/6750c302facf4857b70c543d7b475424

**Comment by JohnathonKoster** [comment]
Improvements to the relative indentation of embedded documents included in:

* `antlers-language-server`: `1.1.1`
* `antlers-formatter`: `1.1.12`
* `prettier-plugin-antlers`: `1.1.16`
* Antlers Toolbox for VS Code: `2.3.6`
