### ISSUE TITLE
Showing error on `or` in partial name

### ISSUE THREAD

**Issue by edalzell** [Stillat/vscode-antlers-language-server#49]
**Describe the bug**

If you have a partial named `foo-or-bar`, you get squiggles complaining about a condition

**Impacted Products**
Which Antlers Toolbox products does this bug apply to?

- [x] Antlers Toolbox for VS Code
- [ ] Antlers Toolbox for VS Code Formatter
- [ ] Formatter CLI
- [ ] Antlers Prettier Plugin
- [ ] Antlers Syntax Highlighting (external systems - not VS Code)

**Versions and Other Plugins/Extensions**
v2.3.6

**To Reproduce**
1. Name a partial `foo-or-bar.antlers.html`
2. Call it `{{ partial:foo-or-bar }}`

**Expected behavior**

no squigglies

<img width="430" alt="CleanShot 2022-09-21 at 12 04 36@2x" src="https://user-images.githubusercontent.com/6069653/191589564-801443bd-730b-436e-b740-8f9501657fee.png">

<img width="608" alt="CleanShot 2022-09-21 at 12 07 04@2x" src="https://user-images.githubusercontent.com/6069653/191589606-bebbb151-9fa1-4670-ad66-9f921691c219.png">

**Comment by JohnathonKoster** [comment]
Resolved with:

Antlers Toolbox for VS Code: `2.3.7`
`antlers-language-server`: `1.1.2`
