### ISSUE TITLE
Antlers tags get corrupted on save

### ISSUE THREAD

**Issue by stefankempf** [Stillat/vscode-antlers-language-server#54]
**Describe the bug**
I have the following snippet on a old page of mine: 
``` 
<title>
    {{ if ! segment_1 }} 
        {{ brand:company_nickname }} &middot; {{brand:company_byline }} 
    {{ elseif seo_title }}
        {{ seo_title }} &middot; {{ brand:company }}
    {{ else }}
        {{ title ?? brand:company_byline }} &middot; {{ brand:company }} 
    {{ /if }}
</title>
```

When I save my file, it gets automatically rewritten into: 
```
<title>
    {{ if !segment_1 }} <Aa3gabdi3fxVe7aL4mpPNz3pJA
    /> {{ elseif seo_title }}
    {{ seo_title }} &middot; {{ brand:company }} {{ else }}
    {{ title ?? brand:company_byline }} &middot; {{ brand:company }}{{ /if }}
</title>
```

**Impacted Products**
Which Antlers Toolbox products does this bug apply to?

- [x] Antlers Toolbox for VS Code
- [ ] Antlers Toolbox for VS Code Formatter
- [ ] Formatter CLI
- [x] Antlers Prettier Plugin
- [ ] Antlers Syntax Highlighting (external systems - not VS Code)

**Versions and Other Plugins/Extensions**
Please include the product version you are reporting a bug for. If you are reporting a bug for products such as Antlers Toolbox for VS Code or the Antlers Prettier Plugin, please include a list of other configured extensions or plugins if you believe they are contributing to the problematic behavior.
- Antlers Toolbox, v2.4.2
- prettier-plugin-antlers, v1.1.19
- prettier-plugin-tailwindcss, v0.2.1

this is my prettier config:
```
{
    "tabWidth": 4,
    "semi": false,
    "singleQuote": true,
    "arrowParens": "avoid",
    "bracketSameLine": true,

    "plugins": [
        "prettier-plugin-antlers",
        "prettier-plugin-tailwindcss"
    ],
    "pluginSearchDirs": false,
    "tailwindConfig": "tailwind.config.js",

    "overrides": [
        {
        "files": "*.antlers.html",
        "vscodeLanguageIds": ["antlers"],
        "options": {
            "parser": "antlers"
        }
        }
    ]
}
```

**Comment by JohnathonKoster** [comment]
Is the provided snippet the only thing in the document? I'm having trouble reproducing this in isolation. Any additional information context would be helpful. Thanks!

**Comment by JohnathonKoster** [comment]
Resolved in the following versions:

* Antlers Toolbox `2.4.3`
* `antlersls`: `1.1.7`
* `antlers-formatter`: `1.1.16`
* `prettier-plugin-antlers`: `1.1.20`
