### ISSUE TITLE
False autocomplete

### ISSUE THREAD

**Issue by stefankempf** [Stillat/vscode-antlers-language-server#57]
**Describe the bug**
I came across the following autocomplete bug. When I write include_home and select the proposed value in the dropdown, it then adds the full modifier to my already written part, which will lead a duplicated characters.

**Impacted Products**
Which Antlers Toolbox products does this bug apply to?

- [x] Antlers Toolbox for VS Code
- [ ] Antlers Toolbox for VS Code Formatter
- [ ] Formatter CLI
- [x] Antlers Prettier Plugin
- [ ] Antlers Syntax Highlighting (external systems - not VS Code)

**Versions and Other Plugins/Extensions**
```json
"prettier-plugin-antlers": "^1.1.20",
"prettier-plugin-tailwindcss": "^0.2.1",
```

**If submitting a formatting bug, please include the template contents below as well as an attachment**
Add any problematic templates here.
```html
{{#
    @name Site Header
    @desc Contains Logo and Main Navigation
#}}
<header class="mx-auto my-0 max-w-page border-setzkasten sm:h-header">
    <a href="/" aria-label="Zurück zur Startseite">
        {{ svg src="setzkasten_logo.svg" class="w-full sm:w-auto sm:h-[calc(var(--layout-header-height)_-_2_*_var(--layout-border-width))]" }}
    </a>
    {{ nav:navigation }}
    <ul>
        <li></li>
    </ul>
    {{ nav:navigation }}
</header>
```
**Additional context**
Please check attached screen recording.
https://user-images.githubusercontent.com/20299885/212659093-4977edde-4713-4a04-84f8-7350aaaf1976.mov

**Comment by JohnathonKoster** [comment]
Resolved in:

* Antlers Toolbox 2.4.5
* `antlers-language-server`: 1.1.9
* `antlers-formatter`: 1.1.17
* `prettier-plugin-antlers`: 1.1.21
