### ISSUE TITLE
{{ user }} tag shorthand reports parameters as unknown

### ISSUE THREAD

**Issue by montemartin** [Stillat/vscode-antlers-language-server#6]
The `{{ user:profile }}` tag allows for shorthand use [without the ':profile'](https://statamic.dev/tags/user-profile#shorthand) method. When used that way the extension reports any parameters used in the 'Problems' panel as "Unknown parameter name".

**Comment by JohnathonKoster** [comment]
Will be available in v 1.0.21 (pending verification on the Visual Studio Marketplace).

Adds parameter support for `{{ user }}` and its `{{ member }}` alias.

**Comment by montemartin** [comment]
Man you're on top of it!
