### ISSUE TITLE
Awkward formatting of `{{# commented code #}}`

### ISSUE THREAD

**Issue by jesseleite** [Stillat/vscode-antlers-language-server#61]
**Describe the bug**
If you surround a block of code with antlers comments...

```antlers
{{# 
{{ collection:articles limit="5" as="articles" }}
    {{ if no_results }}
        <h2 class="text-3xl italic tracking-tight">
            Feel the rhythm! Feel the rhyme! Get on up, it's writing time! Cool writings!
        </h2>
    {{ /if }}
{{ /collection:articles }}
#}}
```

It formats to this...

```antlers
{{#
    {{ collection:articles limit="5" as="articles" }}
    {{ if no_results }}
    <h2 class="text-3xl italic tracking-tight">
    Feel the rhythm! Feel the rhyme! Get on up, it's writing time! Cool writings!
    </h2>
    {{ /if }}
    {{ /collection:articles }}
#}}
```

**Impacted Products**

- [ ] Antlers Toolbox for VS Code
- [ ] Antlers Toolbox for VS Code Formatter
- [x] Formatter CLI
- [x] Antlers Prettier Plugin
- [ ] Antlers Syntax Highlighting (external systems - not VS Code)

**Versions and Other Plugins/Extensions**

VSCode and/or Neovim, tested with both prettier plugin and cli implementation.

**Comment by JohnathonKoster** [comment]
Resolved in:

* Antlers Toolbox (VS Code): 2.4.7
* `antlers-formatter`: 1.1.18
* `prettier-plugin-antlers`: 1.1.25
