### ISSUE TITLE
Takes over formatting in Vue SFC

### ISSUE THREAD

**Issue by daronspence** [Stillat/vscode-antlers-language-server#63]
**Describe the bug**
When enabled in VScode, the Antlers comment syntax takes over for Vue SFC templates.

**Impacted Products**
Which Antlers Toolbox products does this bug apply to?

- [x] Antlers Toolbox for VS Code
- [ ] Antlers Toolbox for VS Code Formatter
- [ ] Formatter CLI
- [ ] Antlers Prettier Plugin
- [ ] Antlers Syntax Highlighting (external systems - not VS Code)

**Versions and Other Plugins/Extensions**
VS code extension 2.4.7

**To Reproduce**
Enable the extension and try to toggle comments in `<template>` code in a Vue SFC. I am using the `CMD+/` shortcut key to toggle the comment for the current/selected line(s).

**Expected behavior**
That Vue's native comments would work.

![CleanShot 2023-03-07 at 00 21 55](https://user-images.githubusercontent.com/4062087/223279204-db5b6e89-0a55-4ca2-a967-c4804aa4d91f.gif)

**Additional context**
N/A

**Comment by JohnathonKoster** [comment]
Thanks for the report!

You can toggle this setting to disable this behavior:

<img width="635" alt="image" src="https://user-images.githubusercontent.com/5232890/223287735-933538bb-6262-46d8-8502-4d765d5da81f.png">

If it at first it doesn't appear to do anything, just load a file with the `.antlers.html` file extension to ensure the extension context has loaded and toggle it again. Thanks!

**Comment by jasonvarga** [comment]
Sorry to comment on an older closed issue. This seems to still happen, even with the setting disabled. I'm using 2.6.1 and the Volar extension for Vue stuff.

**Comment by JohnathonKoster** [comment]
@jasonvarga  Can you give v2.6.2 a try and let me know how things go for you?

**Comment by jasonvarga** [comment]
That fixed it in Vue files, but now (as you probably expect?) only HTML comments are used in Antlers files instead of Antlers comments.

**Comment by JohnathonKoster** [comment]
> That fixed it in Vue files, but now (as you probably expect?) only HTML comments are used in Antlers files instead of Antlers comments.

Can you try enabling the Override HTML comments option for that? That should tell the language server to handle that config  instead of the built in stuff. I've test locally and with the setting enable (on v2.6.2) I can toggle Antlers comments in my Antlers files, and `.vue` files are left alone, etc.

**Comment by jasonvarga** [comment]
When I enable that, it uses Antlers comments in Vue files.

To clarify, we're talking about in single file `.vue` component files. It's within the `template` part which contains HTML.

```vue
<template>
  <div>
    This part of the file contains html.
    Since it's not antlers, it shouldn't use antlers comments.
  </div>
</template>

<script>
  export default {
    // This part of the file contains javascript.
    // Comments were always the double slash JS comments. This part is fine.
  }
</script>
```

**Comment by JohnathonKoster** [comment]
k. Will do some thinking.... not sure of any clear way of continuing to support the comments in all scenarios without a massive rewrite or dropping support for interactivity with other HTML extensions.

**Comment by JohnathonKoster** [comment]
Closing this as the behavior as been improved in v2.6.3
