### ISSUE TITLE
FR: Disabling format in file

### ISSUE THREAD

**Issue by johncarter-** [Stillat/vscode-antlers-language-server#64]
**Which Antlers Toolbox products are you requesting a feature for?**
- [x] Antlers Toolbox for VS Code

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like to be able to turn off formatting for a specific section of code
```
{{# @format false #}}
<div class="dont format me">
Hahaha
</div>
{{# @format true #}}
```

**Describe alternatives you've considered**
None

**Additional context**
Same feature as this in Blade https://marketplace.visualstudio.com/items?itemName=shufo.vscode-blade-formatter#disabling-format-in-file

**Comment by JohnathonKoster** [comment]
This is now available in the following versions:

* Antlers Toolbox (VS Code): 2.5.0
* `antlers-language-server` (npm): 1.2.0
* `antlers-formatter` (npm): 1.2.0
* `prettier-plugin-antlers` (npm): 1.2.0

To disable formatting, we can use the special `{{# format-ignore-start #}}` and `{{# format-ignore-end #}}` Antlers comments:

```antlers
<div>
<div>
{{# format-ignore-start #}}
<div class="class1 class2">
            This section
                will not be formatted.
        </div>
{{# format-ignore-end #}}
</div>
</div>
```

The special formatting comments must appear on separate lines by themselves.
