### ISSUE TITLE
Formatter messes up `{{ unless type == 'section' }}`

### ISSUE THREAD

**Issue by marcorieser** [Stillat/vscode-antlers-language-server#65]
**Describe the bug**
The following antlers code gets messed up by the formatter.

from:
```antlers
{{ unless type == 'section' }}{{ /unless }}
```
to:
```antlers
{{ unless type == pe == 'se }}
{{ /unless }}
```

**Impacted Products**
Which Antlers Toolbox products does this bug apply to?

- [ ] Antlers Toolbox for VS Code
- [ ] Antlers Toolbox for VS Code Formatter
- [ ] Formatter CLI
- [x] Antlers Prettier Plugin
- [ ] Antlers Syntax Highlighting (external systems - not VS Code)

**Versions and Other Plugins/Extensions**
Using `prettier-plugin-antlers` version `1.1.26` in PhpStorm with Prettier.

**Comment by JohnathonKoster** [comment]
Resolved in the following versions:

* Antlers Toolbox (VS Code): `2.4.9`
* `antlers-language-server` (npm): `1.1.14`
* `antlers-formatter` (npm): `1.1.19`
* `prettier-plugin-antlers` (npm): `1.1.27`
