### ISSUE TITLE
Default VSCode HTML Syntax Highlighting is replaced by the Antlers one provided by this plugin.

### ISSUE THREAD

**Issue by jaymeh** [Stillat/vscode-antlers-language-server#66]
**Describe the bug**
Default HTML syntax highlighting is being replaced by the Statamic one. This therefore means that you can't select plain HTML as a formatter anymore within the code editor.

**Impacted Products**
Which Antlers Toolbox products does this bug apply to?

- [x] Antlers Toolbox for VS Code
- [ ] Antlers Toolbox for VS Code Formatter
- [ ] Formatter CLI
- [ ] Antlers Prettier Plugin
- [ ] Antlers Syntax Highlighting (external systems - not VS Code)

**Versions and Other Plugins/Extensions**
V2.5.0

**To Reproduce**
With the Antlers Toolbox plugin installed in VSCode:
1. Create a new index.html
2. CMD + SHIFT + P, and enter "Change Language Mode".
3. Try to select a language mode for HTML (without Antlers Highlighting).
4. It can't be selected and all files need highlighting.
5. Try and comment out something and it just ends up using Antlers convensions (e.g. `{{# </head> #}}`), not the standard VSCode ones.

**Expected behavior**
I would expect that the Antlers plugin should expose a separate HTML language type without overwriting the default one provided by VSCode.

**Comment by JohnathonKoster** [comment]
There are a number of technical reasons things were implemented this way, and have no plans to change this at this time (to reduce the complexity of integrating with the large amount of third-party addons, extensions, etc. that are often used together when building Statamic sites).

The Antlers Toolbox can be disable per-workspace as a workaround.
