### ISSUE TITLE
Stripping code inside ignore tags

### ISSUE THREAD

**Issue by johncarter-** [Stillat/vscode-antlers-language-server#68]
Sorry John. I hope this isn't another user error on my part.

**Describe the bug**
Formatting this:
```
    {{# format-ignore-start #}}
    <title>{{ yield:document_title_section }}{{ document_title ?? title + ' / ' + config:app:name }}{{ /yield:document_title_section }}</title>
    {{# format-ignore-end #}}
```
Ends with this:
```
    {{# format-ignore-start #}}
    <title>{{ yield:document_title_section }}</title>
    {{# format-ignore-end #}}
```

**Impacted Products**
Which Antlers Toolbox products does this bug apply to?

- [x] Antlers Toolbox for VS Code
- [ ] Formatter CLI
- [ ] Antlers Prettier Plugin
- [ ] Antlers Syntax Highlighting (external systems - not VS Code)

**Versions and Other Plugins/Extensions**
v2.5.1

**Comment by JohnathonKoster** [comment]
No worries! A fix has been published in the following versions:

* Antlers Toolbox (VS Code): `2.5.2`
* `antlers-language-server` (NPM): `1.2.2`
* `antlers-formatter` (NPM): `1.2.2`
* `prettier-plugin-antlers` (NPM): `1.2.2`
