### ISSUE TITLE
Avoid tag wrapping in phrasing context

### ISSUE THREAD

**Issue by montemartin** [Stillat/vscode-antlers-language-server#7]
This is a bit of an addition to supporting VSCs html.format options.

By default VSCode will avoid formatting tags listed in `"html.format.unformatted"`. By default it uses the tags defined in HTML spec for [Phrasing content](https://html.spec.whatwg.org/multipage/dom.html#phrasing-content). This is helpful for avoiding issues caused by whitespace. 

Antlers tags inside those rules should probably also not be wrapped. When it doesn't the formatting results are quite strange and could possibly cause whitespace issues in the output. 
```
<p class="text-x-4 align-middle"><span class="ml-1 text-gray-900 uppercase">
   {{ author:name }} &dash;
</span><span class="italic text-gray-800">
    {{ event_date ?? date }}
</span></p>
```

**Comment by JohnathonKoster** [comment]
The unformatted settings will be respected in `1.0.22`

Going to spend some time with #8 before pushing the update.
