### ISSUE TITLE
Additonal closing comment ending on format: #}}#}}

### ISSUE THREAD

**Issue by johncarter-** [Stillat/vscode-antlers-language-server#71]
**Describe the bug**
```
Showing {{ title }} sector

{{# {{ partial src="default" }} #}}

```
Formats to:
```
Showing {{ title }} sector

{{# {{ partial src="default" }} #}}#}}
```

**Impacted Products**
Which Antlers Toolbox products does this bug apply to?

- [x] Antlers Toolbox for VS Code
- [ ] Formatter CLI
- [ ] Antlers Prettier Plugin
- [ ] Antlers Syntax Highlighting (external systems - not VS Code)

**Versions and Other Plugins/Extensions**
v2.6.0

**To Reproduce**

**Expected behavior**
```
Showing {{ title }} sector

{{# {{ partial src="default" }} #}}
```

**If submitting a formatting bug, please include the template contents below as well as an attachment**
Add any problematic templates here.

**Additional context**

**Comment by JohnathonKoster** [comment]
Hey there!

I cannot reproduce using just the submitted template. Would you able to share more of the template where this issue was observed?

Thanks!

**Comment by johncarter-** [comment]
Thanks a lot John. I'll dig it out tomorrow, but I'm pretty sure that's the
entire template.

**Comment by JohnathonKoster** [comment]
Sounds good; let me know if you find anything else that might help!

**Comment by johncarter-** [comment]
Yep that's the entire template. I don't know if there is any more info I could provide to you?

![Code_LbYdf3dGyh](https://user-images.githubusercontent.com/3776888/235619103-3c812632-6db3-438b-aba2-d0008100acac.gif)

**Comment by JohnathonKoster** [comment]
Thanks for the video/screen clip! It's the newline at the end that will trigger this. I'll look into a fix 🙂

**Comment by JohnathonKoster** [comment]
Should be good to go in Antlers Toolbox `2.6.1`, as well as the following:

`antlers-formatter`: 1.2.5
`prettier-plugin-antlers`: 1.2.5
`antlers-language-server`: 1.3.1

**Comment by johncarter-** [comment]
Thanks so much John.
