### ISSUE TITLE
phpstorm version ?

### ISSUE THREAD

**Issue by dadaxr** [Stillat/vscode-antlers-language-server#72]
**Which Antlers Toolbox products are you requesting a feature for?**
- [ ] Antlers Toolbox for VS Code
- [ ] Antlers Toolbox for VS Code Formatter
- [ ] Formatter CLI
- [ ] Antlers Prettier Plugin
- [x] Antlers Syntax Highlighting (external systems - not VS Code)

Would be nice to have a version of this tool for phpstorm (jetbrain's ide) (actually there is another plugin : https://plugins.jetbrains.com/plugin/19203-antlers-language-support but less featured) 

Of course, I don't know how much of work is required to do that, I guess "a lot" as usual ;)

**Comment by JohnathonKoster** [comment]
It is indeed a lot of work, and Stefano has been doing a great job with the PHP Storm support. If you have feature requests I'd create issues here: https://github.com/Konafets/antlers-idea

I have no plans to create a dedicated PHP Storm plugin at this time, but am keeping an eye on LSP support within IntelliJ IDEs (https://intellij-support.jetbrains.com/hc/en-us/community/posts/360001627960-IntelliJ-support-for-Language-Server-Protocol-as-a-client-?sort_by=created_at)

**Comment by dadaxr** [comment]
Sorry to comment a closed issue, but I wanted to share an update on LSP support for intelliJ IDEs ... : https://blog.jetbrains.com/platform/2023/07/lsp-for-plugin-developers/

=> tl;dr : the support of LSP is, as far as i know, only for payed version (not community editions). But PHPStorm and Webstorm (both IDE used by web developper working with laravel, statamic and antlers) are only available in paid edition so ... is not a blocker for an antlers plugin... :)

And sadly the plugin by stephano is laking support for many syntaxes, so the auto-formating is constantly breaking making it almost unusable.

Thanks for your consideration :)

**Comment by JohnathonKoster** [comment]
Oh that is certainly interesting. I missed that update - I'll give it some thought!
