### ISSUE TITLE
Support Prettier 3.0.0 (Antlers Prettier Plugin)

### ISSUE THREAD

**Issue by jimblue** [Stillat/vscode-antlers-language-server#73]
**Which Antlers Toolbox products are you requesting a feature for?**

`Antlers Prettier Plugin`

**Is your feature request related to a problem? Please describe.**

As you probably know, [Prettier 3.0.0](https://github.com/prettier/prettier/releases/tag/3.0.0) has been release yesterday ! 🎉 
Sadly `prettier-plugin-antlers` isn't compatible.

**Describe the solution you'd like**

To make `prettier-plugin-antlers` compatible with this new release it need to support ESM.

Another Prettier plugin very similar to `prettier-plugin-antlers` as already done that : the `prettier-plugin-blade` in their [v1.9.0](https://github.com/shufo/prettier-plugin-blade/releases/tag/v1.9.0).

You can check what to do by looking at [this commit](https://github.com/shufo/prettier-plugin-blade/commit/eb16ae8ee510e169423c813cca04e811bb5e9232).

**Comment by JohnathonKoster** [comment]
Just to set some expectations on this one - this may take some time as I need to do some internal refactoring since this plugin interacts with the prettier APIs

**Comment by jimblue** [comment]
Ok thank you for the update @JohnathonKoster 👍🏼

**Comment by jimblue** [comment]
@JohnathonKoster can you please add links to the issues you're mentioning in your previous message:
> Prettier VS Code extension fails on Windows
> Prettier v3 issues running on Windows CLI

**Comment by JohnathonKoster** [comment]
> @JohnathonKoster could you please add links to the issues you're mentioning in your previous message:
> 
> > * Please use prettier 2.8.8
> > * Prettier VS Code extension fails on Windows
> > * Prettier v3 issues running on Windows CLI

👋

The main issue I keep running into is this one: https://github.com/prettier/prettier-vscode/issues/3062

Beyond that, the large rewrite is largely complete to handle all of the new async stuff, just don't feel comfortable doing any releases until I can reliably run it on my main machines as well 🙂

**Comment by jimblue** [comment]
Oh okay thank for the update and good job referencing this issue in `prettier-vscode` repo... Hopefully this will help a bit.
On my side I'm sorry but I'm running on OSX sadly...

**Comment by JohnathonKoster** [comment]
I'll release v3 support once I am able to verify things work on my end as well (things will still work with prettier 2, however, until support arrives) 👍

**Comment by jimblue** [comment]
Hey @JohnathonKoster, this is just a friendly ping to get some news ? :)

**Comment by JohnathonKoster** [comment]
Hey there!

Mostly still just waiting for things to work in my environment outside of the test suit (still getting hit with that previously linked issue)🙂

**Comment by jimblue** [comment]
Oh okay, so you cannot load the config file with latest prettier on Windows.
I hope prettier team will look at it soon enough. 🤞🏼
Thank you for answering so fast ! 😉 🙏🏼

**Comment by jimblue** [comment]
Hey @JohnathonKoster,
As the issue you're mentioning concern Prettier VScode extension and not Prettier CLI I'm wondering if we could start testing your code with Prettier CLI directly.
I'll be happy to help you if you could share what you already start to code in a new PR. 🙂
Cheers 🍻

**Comment by JohnathonKoster** [comment]
Unlikely at this time:

> with or without the VS Code extension, I hit that same issue

I'm happy with the prettier v2 version at the moment, and will re-assess the situation at a later date 🙂

**Comment by jimblue** [comment]
@JohnathonKoster how are you doing ? 🙂 

The blocking issue as just been closed : https://github.com/prettier/prettier-vscode/issues/3062

Is this working on your side ?

**Comment by JohnathonKoster** [comment]
@jimblue  Not doing too bad, hope you are doing well.

I haven't had time to test, but will add it to my list. This is still on my list (but pretty far down on it in priority after day-job stuff, and other commitments) 🙂

**Comment by stefankempf** [comment]
+1 on this one. I'm starting to get more and more tailwind utilities not getting formated since the tailwind prettier plugin requires prettier v3. Especially now with tailwind's 3.4 `size-*`, `subgrid` and `:has` support its kinda getting outta hand without formatting. I know this Plugin is more a sideproject but still, would be great to get v3 support in 2024 ❤️

**Comment by JohnathonKoster** [comment]
@stefankempf  Currently in progress - working through making sure that the current non-prettier version continues to work non-async, while also adding support for async versions of a number of internal methods to support prettier v3 🙂

**Comment by JohnathonKoster** [comment]
@jimblue  @stefankempf 

The Prettier 3 plugin is now generally available. You will need to use version 2 of the `prettier-plugin-antlers`:

```bash
npm install prettier-plugin-antlers@^2 --save-dev
```

The format of the `.prettierrc` file has also changed. You should use a setup similar to the following (not the lack of specifying `node_modules` within the Prettier plugin paths):

```json
{
    "plugins": [
        "prettier-plugin-antlers",
        "prettier-plugin-tailwindcss"
    ],
    "overrides": [
        {
            "files": [
                "*.antlers.html"
            ],
            "options": {
                "parser": "antlers"
            }
        }
    ]
}
```

Finally, if you are using Visual Studio Code and receive errors stating that no formatter for Antlers could be found after making these changes (upgrading to Prettier 3, the new Prettier extension, and the updated Antlers plugin), you can update your VS Code settings JSON file to have changes similar to the following:

```json
{
  "[antlers]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "prettier.documentSelectors": [
    "**/*.antlers.html"
  ]
}
```

**Comment by stefankempf** [comment]
Now I have bad conscience motivating you to work on it on new years eve. 🙈 nevertheless, those are some great news. I'll go and test it out asap. Thanks a lot and happy new year!

**Comment by JohnathonKoster** [comment]
No worries - I was already working to wrap things up yesterday :)
