### ISSUE TITLE
Normal HTML comments don't render the highlighting properly

### ISSUE THREAD

**Issue by yCodeTech** [Stillat/vscode-antlers-language-server#78]
**Describe the bug**
When this extension is installed, any commented out HTML with normal comment tags `<!-- -->` don't highlight properly as comments, see image.
![image](https://github.com/Stillat/vscode-antlers-language-server/assets/31927084/f9bdbfd0-d7da-427d-8da6-5b91ca7eb8fb)
The comment highlighting works when this extension is disabled. 

**Impacted Products**
Which Antlers Toolbox products does this bug apply to?

- [x] Antlers Toolbox for VS Code
- [ ] Formatter CLI
- [ ] Antlers Prettier Plugin
- [ ] Antlers Syntax Highlighting (external systems - not VS Code)

**Versions and Other Plugins/Extensions**
Please include the product version you are reporting a bug for. If you are reporting a bug for products such as Antlers Toolbox for VS Code or the Antlers Prettier Plugin, please include a list of other configured extensions or plugins if you believe they are contributing to the problematic behavior.

VScode version: 1.83.1
Antlers Toolbox version: 2.6.8

**To Reproduce**
N/A

**Expected behavior**
The commented out HTML should appear all green as a comment should.

**If submitting a formatting bug, please include the template contents below as well as an attachment**
N/A

**Additional context**
N/A

**Comment by JohnathonKoster** [comment]
Thanks for the report! Will adjust the grammar in the next release :)

**Comment by JohnathonKoster** [comment]
Scheduled for v2.6.9
