### ISSUE TITLE
Issue with view-variables upon formatting

### ISSUE THREAD

**Issue by AndreasSchantl** [Stillat/vscode-antlers-language-server#79]
**Describe the bug**
When saving a file that uses view variables, ``view`` is being replicated multiple times.

Note: format on save is enabled in VSCode and the formatter is set to Antlers Toolbox.

**Impacted Products**
Which Antlers Toolbox products does this bug apply to?

- [x] Antlers Toolbox for VS Code
- [ ] Formatter CLI
- [ ] Antlers Prettier Plugin
- [ ] Antlers Syntax Highlighting (external systems - not VS Code)

**Versions and Other Plugins/Extensions**
- Antlers Toolbox: v2.6.9
- Prettier: v10.1.0 (official)
- Laravel Pint v1.1.4 (by Open Southeners)

**To Reproduce**
Enable Antlers Toolbox, go to a file that uses view variables and see ``view`` being added multiple times.

https://github.com/Stillat/vscode-antlers-language-server/assets/9936988/143be20b-a489-46fc-a0bf-362ce9f62e35

**If submitting a formatting bug, please include the template contents below as well as an attachment**
```
---
background:
  default: 'bg-green-500/80 p-2 md:p-3 3'
button:
  default: 'backdrop-blur-md bg-green-500/80 hover:bg-green-500 focus:bg-green-500'
---

<div
     class="absolute inset-0 container mx-auto px-2 h-full flex flex-col justify-end pb-10 z-10 header-text {{ site:handle }}">
    <div>
        <div class="inline-block">
            {{ if heading }}
                <div
                     class="headings inline-flex flex-col items-baseline lg:text-6xl md:text-4xl text-2xl text-white backdrop-blur-md p-2 font-bold leading-tight tracking-wider">
                    {{ heading }}
                </div>
            {{ /if }}
            {{ if text }}
                <div
                     class="flex flex-col items-baseline lg:text-xl md:text-base text-sm leading-snug max-w-xl {{ view:background['default'] }} text-white {{ heading ?= 'pt-4' }} font-light">
                    {{ text }}
                </div>
            {{ /if }}
            {{ if link_text }}
                <div class="pt-3">
                    <a
                       href="{{ link }}"
                       class="inline-flex items-center space-x-2 px-3 text-white focus:outline-none font-medium md:text-lg text-base uppercase border-2 border-white {{ view:button['default'] }} group">
                        <span class="py-1">{{ link_text }}</span>
                    </a>
                </div>
            {{ /if }}
        </div>
    </div>
</div>
```

**Comment by AndreasSchantl** [comment]
Rechecking this again currently. It's only happening in this file for some reason.

**Comment by AndreasSchantl** [comment]
Gotcha: It's only happening if I pass strings into it.

This works: ``{{ view:fontsize[font_size] }}``
This doesn't: ``{{ view:fontsize['default'] }}``

**Comment by JohnathonKoster** [comment]
Thanks for all the extra info! Will check it out sometime later today

**Comment by JohnathonKoster** [comment]
Resolved in:

* Antlers Toolbox (VS Code): 2.6.10
* `antlers-language-server`: 1.3.9
* `antlers-formatter`: 1.2.8
* `prettier-plugin-antlers`: 1.2.8

**Comment by AndreasSchantl** [comment]
Thanks for the ridiculously fast update! ❤️
