### ISSUE TITLE
Antlers comments causing seeming random issues

### ISSUE THREAD

**Issue by montemartin** [Stillat/vscode-antlers-language-server#8]
I've run into some strange edgecases with Antlers comments. They all seem to happen sort of randomly, I haven't figured out exactly what causes each, or been able to replicate them consistently. 

First, sometimes comments get nested as if they are paired tags.
```
<div>
{{#  comment 1 #}}
{{# comment 2 #}}
{{ variable }}
</div>
``` 
becomes
```
<div>
    {{#  comment 1 #}}
        {{# comment 2 #}}
            {{ variable }}
        </div>
``` 

Another issue is some comments cause the last few lines to get duplicated with every format. (I ended up with a LOT of `</div></aside>` in one file). 

The last thing was at some point while trying to figure out the duplication issue I ended up with an ID string in the middle of my opening <div> tag. I haven't been able to replicate it but from memory it was something like`<div [ANTLR id="long_string_of_numbers"] class="classes">`

One thing I thought was causing the issues was having a `#` inside the comment. It first started when I put an anchor linked URL in a comment. Removing the anchor stopped the issues at the time, but with further testing it's still happening randomly with plain text comments.

**Comment by JohnathonKoster** [comment]
Thanks for all the extra details - I had noticed the duplication thing a few times, but could never get it to happen consistently (and what a weird issue, in general).

The extra details really help! Thanks!

**Comment by JohnathonKoster** [comment]
Changes made to resolve issues in 1.0.22:

* Added the `<IF />` and `<ANTLR />` intermediate HTML tags to the content unformatted list before formatting, preventing the closing pairs from being someplace unexpected (all Antlers code is transformed into HTML as part of a pre-processing step, and converted back once complete). Also helps to prevent incorrectly-aligned comment tags (but may not prevent it in all situations)
* Corrected an issue where the wrong end position was being used in the replacement range. When this was less than the replacement text, the final lines of the document would be duplicated
* Extracts YAML front matter before formatting the document, and re-inserts it once formatted

**Comment by montemartin** [comment]
Not sure if it's any additional help, but I just found a bunch of empty files at `/storage/antlers-language-server/error-{timestamp).json` with timestamps from when I was trying to debug this. Each one contains a single empty json object.

**Comment by JohnathonKoster** [comment]
@JohnathonKoster NTS: Close with Jan/Feb release as the core issue was identified (misclassification of Comment regions) and has been resolved with that work.
