### ISSUE TITLE
"Missing required parameter" on the closing tag of partials 

### ISSUE THREAD

**Issue by isaackearl** [Stillat/vscode-antlers-language-server#84]
**Describe the bug**
When using partials in antlers, I'm getting "Missing required parameter: <name of parameter> antlers(ANTLR_517)" on all my closing tags.  Take a look at screenshot.

<img width="500" alt="image" src="https://github.com/Stillat/vscode-antlers-language-server/assets/9354830/e70c4279-3e6f-4754-801d-33a6da20ac4a">

And when I hover over the red line

<img width="508" alt="image" src="https://github.com/Stillat/vscode-antlers-language-server/assets/9354830/3108535e-6558-46f2-acd7-9f50c4bda90d">

**Impacted Products**
Which Antlers Toolbox products does this bug apply to?

- [ x] Antlers Toolbox for VS Code
- [ ] Formatter CLI
- [ ] Antlers Prettier Plugin
- [ ] Antlers Syntax Highlighting (external systems - not VS Code)

**Versions and Other Plugins/Extensions**
I only have the Antlers toolbox installed.  Prettier is disabled for this project and I don't have the formatter or anything like that.  It is simply Antlers Toolbox.

**To Reproduce**
Here is my partial, as you can see the param for variant has a *, which marks it as required.  

`{{#
    @name Text
    @desc A reusable text component to keep consistency.
    @param* variant titleXL, titleLG, titleMD, titleSM, bodyLG, bodyMD, bodySM
    @param align left, center, right - default left
#}}

<{{ as or 'p' }}
    class="
    {{ switch(
        (variant == 'titleXXXL') => 'text-6xl text-white font-bold',
        (variant == 'titleXXL') => 'text-4xl text-white font-bold',
        (variant == 'titleXL') => 'text-2xl text-white font-bold',
        (variant == 'titleLG') => 'text-2xl text-primary font-bold',
        (variant == 'titleMD') => 'text-xl text-primary font-bold',
        (variant == 'titleSM') => 'text-lg text-primary font-bold',
        (variant == 'bodyLG') => 'text-lg text-black',
        (variant == 'bodyMD') => 'text-md text-black',
        (variant == 'bodySM') => 'text-sm text-black',
        () => 'text-md'
    )}}

    {{ switch(
        (align == 'right') => 'text-right',
        (align == 'center') => 'text-center',
        () => 'text-left'
    )}}

    {{ class }}
">
    {{ slot }}
</{{ as or 'p' }}>

`

**Expected behavior**
it only tells me I'm missing a required parameter when I'm on the opening tag of my partial

**Comment by JohnathonKoster** [comment]
Thanks for the report! I'll take a look and work on an update sometime early this week :)

**Comment by JohnathonKoster** [comment]
Resolved in the following versions:

* Antlers Toolbox for VS Code: `2.6.14`
* `antlersls` (standalone language server): `1.3.11`
