### ISSUE TITLE
Not seeing an `antlers.json` file within project / no autocomplete for fields, collections

### ISSUE THREAD

**Issue by aaronbushnell** [Stillat/vscode-antlers-language-server#89]
**Describe the bug**
Sorry for submitting another bug report here—I might be doing something wrong. I've got the extension installed, but I'm not seeing an `antlers.json` file being generated for my project (which seems to be the way to determine if the extension is working off your Statamic project).

I've tried swapping the "Antlers Language Server: Language Version" from `regex` to `runtime` and neither seemed to help in my case.

Happy to supply any debugging information you might need for this one!

I'm not sure if this is related, but when I use `{{ }}` in an Antlers file I get this output in the Output area of VS Code:

```
2024-06-06 08:28:09.943 [error] name must not be falsy: Error: name must not be falsy
    at Function.validate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:151:18100)
    at new h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:151:18395)
    at asDocumentSymbol (/Users/aaron/.vscode/extensions/stillat-llc.vscode-antlers-2.6.18/client/node_modules/vscode-languageclient/lib/common/protocolConverter.js:522:22)
    at Array.map (<anonymous>)
    at Object.asDocumentSymbols (/Users/aaron/.vscode/extensions/stillat-llc.vscode-antlers-2.6.18/client/node_modules/vscode-languageclient/lib/common/protocolConverter.js:519:23)
    at /Users/aaron/.vscode/extensions/stillat-llc.vscode-antlers-2.6.18/client/node_modules/vscode-languageclient/lib/common/client.js:1108:70
    at h.provideDocumentSymbols (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:98122)
``` 

**Impacted Products**
Which Antlers Toolbox products does this bug apply to?

- [x] Antlers Toolbox for VS Code
- [ ] Formatter CLI
- [ ] Antlers Prettier Plugin
- [ ] Antlers Syntax Highlighting (external systems - not VS Code)

**Versions and Other Plugins/Extensions**
- Antlers Toolbox (2.6.18)
- VS Code (1.90.0)
- statamic/cms (5.7.1 — in case this is helpful!)

**To Reproduce**
- Install extension
- Open a Statamic project
- Attempt to generate the `antlers.json` file using the "Reload Statamic Project Details" command palette item

**Comment by JohnathonKoster** [comment]
The extension won't publish an `antlers.json` file (or shouldn't) when running the `Reload Statamic Project Details` command. Do you get any suggestions at all if you place the cursor like so and manually trigger the completions shortcut `{{ | }}`?

![image](https://github.com/Stillat/vscode-antlers-language-server/assets/5232890/9208b15a-2a19-4f28-97bf-190608130c58)

An easy way to tell if the extension has loaded is if syntax highlighting works and the language has changed to `HTML (Statamic Antlers)`:

![image](https://github.com/Stillat/vscode-antlers-language-server/assets/5232890/38e6fe78-23d6-4fea-a99f-b2147794bd2a)

I'm not able to reproduce this at the moment, so any extra info about the project itself or other installed extensions would be helpful. Thanks!

**Comment by aaronbushnell** [comment]
Ah, nevermind, @JohnathonKoster, this was user error here! While I had some autocomplete the field names weren't autocompleting for me because I was in a dynamic template I was using for a Replicator field.

As soon as I tested out this in another template:
```antlers
{{ collection:blog }}

{{ /collection:blog }}
```
And typed out `{{ su` I got the `summary` field I expected. Thank you!
