### ISSUE TITLE
Suggestions are not showing up or at the wrong place

### ISSUE THREAD

**Issue by helloDanuk** [Stillat/vscode-antlers-language-server#9]
I have problems getting the extension to work properly. There are some suggestion popping up just after typing {{ without a space, which would get `{{collection` but after typing {{ with a space no more are proposed. The word partial is not proposed at all, with modifiers it the same problem with the space and comments with cmd + / (shift 7) are something written as HTML  or as Antlers {{# #}}. In the end it just does not feel right.

**Suggestion after typing {{ or | without a space:**
<img width="822" alt="Bildschirmfoto 2021-06-04 um 00 40 04" src="https://user-images.githubusercontent.com/8265902/120800735-9303a300-c540-11eb-8213-d12285ff0605.png">
<img width="439" alt="Bildschirmfoto 2021-06-04 um 14 33 08" src="https://user-images.githubusercontent.com/8265902/120801873-08bc3e80-c542-11eb-8ab2-5a9ae29beb83.png">

**No suggestion after typing a space:**
<img width="822" alt="Bildschirmfoto 2021-06-04 um 00 42 52" src="https://user-images.githubusercontent.com/8265902/120800765-9dbe3800-c540-11eb-9261-03953d06d575.png">
<img width="227" alt="Bildschirmfoto 2021-06-04 um 14 33 25" src="https://user-images.githubusercontent.com/8265902/120801828-fb9f4f80-c541-11eb-9791-2950cef9f01e.png">

Maybe it's just a settings issue, but I haven't found anything about in the docs. If this is the case, I am sorry to bother you. But a would be thankful for an advice.

I even tried it with a brand new VS Code installation on another machine with only this extension installed. macOS, VS Code are up to date. I've tried with global enabled and with 'Add to workspace recommodations'.

.antlers.json gets generated by the way.

**Comment by JohnathonKoster** [comment]
There are definitely improvements to be made with the underlying suggestions engine. Would you mind sending your resources and `.antlers.json` file as a ZIP archive to hello@stillat.com (do not upload here) - to help rule out possible interaction issues between the generated files and core setup?

Thanks!

**Comment by JohnathonKoster** [comment]
@JohnathonKoster : Close with Jan/Feb release as that makes improvements to all issues mentioned here.
