### ISSUE TITLE
Escaped double quotes are removed when formatting

### ISSUE THREAD

**Issue by rogervanwile** [Stillat/vscode-antlers-language-server#90]
**Describe the bug**
I'm using prettify to format my antlers files. When there is a escaped double quote in a attribute, the attribute will be wrong formatted and after a second prettifing, removed. 

**Impacted Products**
Which Antlers Toolbox products does this bug apply to?

- [ ] Antlers Toolbox for VS Code
- [ ] Formatter CLI
- [x] Antlers Prettier Plugin
- [ ] Antlers Syntax Highlighting (external systems - not VS Code)

**Versions and Other Plugins/Extensions**

prettier: 3.3.2
prettier-plugin-antlers: 2.0.3

**To Reproduce**

Create a *.antlers.html template with the following code:

```
{{ partial:button attr="x-bind:disabled=\"submitting\"" }}
```

Run prettify once:

```
{{ partial:button attr="x-bind:disabled="submitting"" }}
```

After a second prettify run:

```
{{ partial:button attr="x-bind:disabled=" }}
```

The last `attr` is formatted wrong after the first run and removed in the second run.

**Expected behavior**

The attr should stay untouched. The syntax `attr="x-bind:disabled=\"submitting\""` is correct.

**If submitting a formatting bug, please include the template contents below as well as an attachment**
Add any problematic templates here.

**Additional context**

**Comment by JohnathonKoster** [comment]
Thanks for the report!

**Comment by JohnathonKoster** [comment]
Resolved in the following versions:

* `prettier-plugin-antlers`: 2.0.4
* `antlers-formatter`: 1.2.13
* Antlers Toolbox for VS Code: 2.6.19
