### ISSUE TITLE
Underlines appear strangely in code

### ISSUE THREAD

**Issue by replete** [Stillat/vscode-antlers-language-server#92]
**Describe the bug**
Some tags in HTML views appear unexpectedly underlined
![Screenshot 2024-07-06 at 16 35 12](https://github.com/Stillat/vscode-antlers-language-server/assets/812139/c6230eaa-5f5f-49e9-b976-96a49c6e096c)

**Impacted Products**
Which Antlers Toolbox products does this bug apply to?

- [x] Antlers Toolbox for VS Code
- [ ] Formatter CLI
- [ ] Antlers Prettier Plugin
- [ ] Antlers Syntax Highlighting (external systems - not VS Code)

**Versions and Other Plugins/Extensions**
Please include the product version you are reporting a bug for. If you are reporting a bug for products such as Antlers Toolbox for VS Code or the Antlers Prettier Plugin, please include a list of other configured extensions or plugins if you believe they are contributing to the problematic behavior.

VSCodium 1.90.2
(I appreciate you might not want to support this build of vscode, but I thought it best to report it anyway, vscodium is a straight build of vscode without the trackers and non-FLOSS microsoft licensing and most plugins work the same)

**To Reproduce**
Install plugin.
Appears fine initially, then underlines appear along with warnings

**Expected behavior**

No underlines should appear anywhere.

**If submitting a formatting bug, please include the template contents below as well as an attachment**
Add any problematic templates here.

**Additional context**

**Comment by JohnathonKoster** [comment]
VS Code underlines things it thinks are links, such as the content in the `href=""` of HTML tags. The partial is underlined since the language server itself _made_ those into links, and can use the configured shortcut to navigate to the source of that partial.

**Comment by replete** [comment]
I thought it was an error here because the underline starts at the second curly brace.

![Screenshot 2024-07-06 at 17 35 02](https://github.com/Stillat/vscode-antlers-language-server/assets/812139/ac587f44-1891-4a12-b3f0-89f7f92af1d4)

**Comment by JohnathonKoster** [comment]
Just a small offset thing. Do you see any errors in the problems window when it shows up?

**Comment by replete** [comment]
No problems. I thought I had an extension compatibility issue, that's why I jumped here so quickly. Thanks for writing this plugin by the way.

While I'm here, is it possible to disable this newline-in-curly-brace behaviour when in script or style tags?
![Screenshot 2024-07-07 at 11 13 53](https://github.com/Stillat/vscode-antlers-language-server/assets/812139/b98bcc00-5c33-46b6-8fa5-5c20cb547d86)
