### ISSUE TITLE
Partial with a hyphen and the word and in the source filename causes an error

### ISSUE THREAD

**Issue by dannyuk1982** [Stillat/vscode-antlers-language-server#95]
**Describe the bug**
If you have a partial containing a hyphen, i.e.

`{{ partial:image-and-quote }}`

This causes an error:

`[ANTLR_001] Expecting operand, found T_AND near "-".`

It's fine with this syntax:

`{{ partial src="image-and-quote" }}`

Or without the and

`{{ partial:image-quote }}`

**Impacted Products**
Which Antlers Toolbox products does this bug apply to?

- [X] Antlers Toolbox for VS Code

**Versions and Other Plugins/Extensions**
VS Code Version: 1.92.0

**To Reproduce**
As above

**Expected behavior**
No error as hyphens are valud

**If submitting a formatting bug, please include the template contents below as well as an attachment**
As above

**Comment by JohnathonKoster** [comment]
Resolved in the following versions:

* Antlers Toolbox for VS Code: 2.6.20
* `antlersls`: 1.3.13
* `antlers-formatter`: 1.2.14
* `prettier-plugin-antlers`: 2.0.5

**Comment by dannyuk1982** [comment]
Thanks for the super quick fix, amazing stuff!
