### ISSUE TITLE
Unexpected operator error when using multidimensional array in ternary or gatekeeper statement

### ISSUE THREAD

**Issue by o1y** [Stillat/vscode-antlers-language-server#97]
**Describe the bug**
When using the ternary statement or gatekeeper with a multidimensional array, you get an (invalid) unexpected operator error.

```bash
[ANTLR_068] Unexpected operator while parsing input text.antlers(ANTLR_068)
[ANTLR_002] Unexpected end of input; expecting operand for operator T_VFBK near "?=".antlers(ANTLR_002)
```

**Impacted Products**
Which Antlers Toolbox products does this bug apply to?

- [x] Antlers Toolbox for VS Code
- [ ] Formatter CLI
- [ ] Antlers Prettier Plugin
- [ ] Antlers Syntax Highlighting (external systems - not VS Code)

**Versions and Other Plugins/Extensions**
v2.6.20

**To Reproduce**
```antlers
{{ _class = column_size > 0 ?= _column_sizes['md'][column_size] }}
```
If you remove the `md` key, you won't see any errors. Workaround is to use additional single braces like so:

```antlers
{{ _class = column_size > 0 ?= {_column_sizes['md'][column_size]} }}
```

<img width="1066" alt="Bildschirmfoto 2024-08-07 um 11 14 55" src="https://github.com/user-attachments/assets/45832889-e870-4c7b-8297-91d893e01049">

**Expected behavior**
It shouldn't show any syntax error.

**Comment by JohnathonKoster** [comment]
Resolved in the following versions:

* `antlers-language-server`: 1.3.14
* Antlers Toolbox for VS Code: 2.6.21
